---
# tasks file for yq

- name: Include tasks to install yq
  ansible.builtin.include_tasks: install-yq.yaml
  when: yq_state == 'present'

- name: Include tasks to remove yq
  ansible.builtin.include_tasks: remove-yq.yaml
  when: yq_state == 'absent'
