---
- name: Check if installed
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "command -v {{ kanata_binary_name }}"
  register: kanata_installed
  changed_when: false
  failed_when: kanata_installed.rc != 0 and kanata_installed.stderr != ""

- name: Get installed version data
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "{{ kanata_binary_name }} --version"
  register: kanata_installed_version_data
  changed_when: false
  failed_when: "kanata_installed_version_data.rc != 0 or (kanata_installed_version_data.rc == 0 and 'kanata' not in kanata_installed_version_data.stdout)"
  when: kanata_installed.rc == 0

- name: Set installed version
  ansible.builtin.set_fact:
    kanata_installed_version: "{{ 'v' + kanata_installed_version_data.stdout.split()[1] if kanata_installed.rc == 0 else '' }}"

- name: Get the latest release data
  ansible.builtin.uri:
    url: "{{ kanata_latest_version_url }}"
    return_content: true
    headers:
      Authorization: "{{ 'Bearer ' + github_pat if github_pat is defined else omit }}"
  register: kanata_latest_release_data
  retries: 3
  delay: 5

- name: Set the release version
  ansible.builtin.set_fact:
    kanata_release_version: "{{ kanata_latest_release_data.json.tag_name if kanata_version == 'latest' else kanata_version }}"

- name: Download and install
  when: kanata_force_download or kanata_installed_version != kanata_release_version
  block:
    - name: Create download temporary directory
      ansible.builtin.tempfile:
        state: directory
        prefix: kanata_
      register: kanata_tempdir

    - name: Get sha256 text content
      ansible.builtin.set_fact:
        sha256_text: "{{ kanata_latest_release_data.json.body.split('sha256 checksums')[1].split('```')[1] | trim }}"

    - name: Get search word rhs
      ansible.builtin.set_fact:
        search_word_rhs: "{{ kanata_artifact_basename }}"

    - name: Extract checksum
      ansible.builtin.set_fact:
        kanata_checksum: "{{ kanata_checksum_algorithm }}:{{ sha256_text | regex_search('([a-f0-9]{64})\\s+.*' ~ search_word_rhs) | split | first }}"

    - name: Download artifact
      ansible.builtin.get_url:
        url: "{{ kanata_artifact_download_url }}"
        dest: "{{ kanata_tempdir.path }}"
        checksum: "{{ kanata_checksum }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x

    - name: Copy binary
      ansible.builtin.copy:
        src: "{{ kanata_tempdir.path }}/{{ kanata_artifact_basename }}"
        dest: "{{ kanata_binary_path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x
        remote_src: true

    - name: Cleanup temp files
      ansible.builtin.file:
        path: "{{ kanata_tempdir.path }}"
        state: absent
