---
# tasks file for kanata

- name: Include tasks to install kanata
  ansible.builtin.include_tasks: install-kanata.yaml
  when: kanata_state == 'present'

- name: Include tasks to remove kanata
  ansible.builtin.include_tasks: remove-kanata.yaml
  when: kanata_state == 'absent'
