---
# tasks file for dnf

- name: Copy DNF configuration file
  ansible.builtin.copy:
    src: dnf.conf
    dest: /etc/dnf/
    owner: root
    group: root
    mode: "0644"

- name: Add RPM Fusion free and nonfree GPG keys
  ansible.builtin.rpm_key:
    key: "{{ item }}"
    state: present
  loop:
    - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020"
    - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"

- name: Enable RPM Fusion free and nonfree repositories
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts.distribution_version }}.noarch.rpm"
    - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts.distribution_version }}.noarch.rpm"
