---
# tasks file for hostctl

- name: Include tasks to install hostctl
  ansible.builtin.include_tasks: install-hostctl.yaml
  when: hostctl_state == 'present'

- name: Include tasks to remove hostctl
  ansible.builtin.include_tasks: remove-hostctl.yaml
  when: hostctl_state == 'absent'
