---
# tasks file for rust

- name: Include tasks to install rust
  ansible.builtin.include_tasks: install-rust.yaml
  when: rust_state == 'present'

- name: Include tasks to remove rust
  ansible.builtin.include_tasks: remove-rust.yaml
  when: rust_state == 'absent'
