---
# tasks file for gh-cli

- name: Get the latest GitHub release data
  ansible.builtin.uri:
    url: https://api.github.com/repos/cli/cli/releases/latest
    return_content: true
  register: gh_latest_release_data

- name: Set the latest release version
  ansible.builtin.set_fact:
    gh_latest_release_version: "{{ gh_latest_release_data.json.tag_name }}"

- name: Set the release artifact
  vars:
    arch_name:
      amd: amd64
      arm: arm64
  ansible.builtin.set_fact:
    gh_release_artifact: "gh_{{ gh_latest_release_version[1:] }}_{{ ansible_facts.system | lower }}_{{ arch_name[archs.get(ansible_facts.architecture)] | default(ansible_facts.architecture) }}"

- name: Create download temporary directory
  ansible.builtin.tempfile:
    state: directory
    prefix: gh_
  register: gh_tempdir

- name: Unarchive artifact
  ansible.builtin.unarchive:
    src: "https://github.com/cli/cli/releases/download/{{ gh_latest_release_version }}/{{ gh_release_artifact }}.tar.gz"
    dest: "{{ gh_tempdir.path }}"
    remote_src: true

- name: Copy binary
  ansible.builtin.copy:
    src: "{{ gh_tempdir.path }}/{{ gh_release_artifact }}/bin/gh"
    dest: /usr/local/bin
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: a+x
    remote_src: true

- name: Cleanup temp files
  ansible.builtin.file:
    path: "{{ gh_tempdir.path }}"
    state: absent
