---
# tasks file for firefox

- name: Install Firefox
  ansible.builtin.dnf:
    name: firefox
    state: latest

- name: Ensure policies directory exists
  ansible.builtin.file:
    path: /etc/firefox/policies
    state: directory
    owner: root
    group: root
    mode: "0755"
    modification_time: preserve
    access_time: preserve

- name: Copy policies.json
  ansible.builtin.copy:
    src: policies.json
    dest: /etc/firefox/policies/
    owner: root
    group: root
    mode: "0755"

- name: Copy autoconfig.js
  ansible.builtin.copy:
    src: autoconfig.js
    dest: /usr/lib64/firefox/defaults/pref/
    owner: root
    group: root
    mode: "0755"

- name: Copy firefox.cfg
  ansible.builtin.copy:
    src: firefox.cfg
    dest: /usr/lib64/firefox/
    owner: root
    group: root
    mode: "0755"
