---
# tasks file for lazydocker

- name: Include tasks to install lazydocker
  ansible.builtin.include_tasks: install-lazydocker.yaml
  when: lazydocker_state == 'present'

- name: Include tasks to remove lazydocker
  ansible.builtin.include_tasks: remove-lazydocker.yaml
  when: lazydocker_state == 'absent'
