---
- name: Check if installed
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "command -v {{ k9s_binary_name }}"
  register: k9s_installed
  changed_when: false
  failed_when: k9s_installed.rc != 0 and k9s_installed.stderr != ""

- name: Get installed version data
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "{{ k9s_binary_name }} version"
  register: k9s_installed_version_data
  changed_when: false
  failed_when: "k9s_installed_version_data.rc != 0 or (k9s_installed_version_data.rc == 0 and 'Version' not in k9s_installed_version_data.stdout)"
  when: k9s_installed.rc == 0

- name: Set installed version
  ansible.builtin.set_fact:
    k9s_installed_version: "{{ 'v' + k9s_installed_version_data.stdout_lines[7].split(':')[1].split('v')[1] if k9s_installed.rc == 0 else '' }}"

- name: Get the latest GitHub release data
  ansible.builtin.uri:
    url: https://api.github.com/repos/derailed/k9s/releases/latest
    return_content: true
    headers:
      Authorization: "{{ 'Bearer ' + github_pat if github_pat is defined else omit }}"
  register: k9s_latest_release_data

- name: Set the release version
  ansible.builtin.set_fact:
    k9s_release_version: "{{ k9s_latest_release_data.json.tag_name if k9s_version == 'latest' else k9s_version }}"

- name: Download and install
  when: k9s_installed_version != k9s_release_version
  block:
    - name: Set the release artifact
      vars:
        arch_name:
          amd: amd64
          arm: arm64
      ansible.builtin.set_fact:
        k9s_release_artifact: "k9s_{{ ansible_facts.system }}_{{ arch }}"

    - name: Create download temporary directory
      ansible.builtin.tempfile:
        state: directory
        prefix: k9s_
      register: k9s_tempdir

    - name: Unarchive artifact
      ansible.builtin.unarchive:
        src: "https://github.com/derailed/k9s/releases/download/{{ k9s_release_version }}/{{ k9s_release_artifact }}.tar.gz"
        dest: "{{ k9s_tempdir.path }}"
        remote_src: true

    - name: Copy binary
      ansible.builtin.copy:
        src: "{{ k9s_tempdir.path }}/k9s"
        dest: "{{ k9s_binary_path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x
        remote_src: true

    - name: Cleanup temp files
      ansible.builtin.file:
        path: "{{ k9s_tempdir.path }}"
        state: absent
