---
# tasks file for k9s

- name: Include tasks to install k9s
  ansible.builtin.include_tasks: install-k9s.yaml
  when: k9s_state == 'present'

- name: Include tasks to remove k9s
  ansible.builtin.include_tasks: remove-k9s.yaml
  when: k9s_state == 'absent'
