---
# tasks file for taskfile

- name: Get the latest GitHub release data
  ansible.builtin.uri:
    url: https://api.github.com/repos/go-task/task/releases/latest
    return_content: true
  register: task_latest_release_data

- name: Set the release version
  ansible.builtin.set_fact:
    task_latest_release_version: "{{ task_latest_release_data.json.tag_name }}"

- name: Set the release artifact
  vars:
    arch_name:
      amd: amd64
      arm: arm64
  ansible.builtin.set_fact:
    task_release_artifact: "task_{{ ansible_facts.system | lower }}_{{ arch_name[archs.get(ansible_facts.architecture)] | default(ansible_facts.architecture) }}"

- name: Create download temporary directory
  ansible.builtin.tempfile:
    state: directory
    prefix: task_
  register: task_tempdir

- name: Unarchive artifact
  ansible.builtin.unarchive:
    src: "https://github.com/go-task/task/releases/download/{{ task_latest_release_version }}/{{ task_release_artifact }}.tar.gz"
    dest: "{{ task_tempdir.path }}"
    remote_src: true

- name: Copy binary
  ansible.builtin.copy:
    src: "{{ task_tempdir.path }}/task"
    dest: /usr/local/bin
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: a+x
    remote_src: true

- name: Cleanup temp files
  ansible.builtin.file:
    path: "{{ task_tempdir.path }}"
    state: absent
