---
- name: Check if installed
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "command -v {{ atlas_binary_name }}"
  changed_when: false
  register: atlas_installed
  failed_when: atlas_installed.rc != 0 and atlas_installed.stderr != ""

- name: Get installed version data
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "{{ atlas_binary_name }} version"
  register: atlas_installed_version_data
  changed_when: false
  failed_when: "atlas_installed_version_data.rc != 0 or (atlas_installed_version_data.rc == 0 and 'atlas version' not in atlas_installed_version_data.stdout)"
  when: not atlas_installed.failed

- name: Set installed version
  ansible.builtin.set_fact:
    atlas_installed_version: "{{ atlas_installed_version_data.stdout_lines[0].split()[2] if atlas_installed_version_data.failed else '' }}"

- name: Get the latest GitHub release
  ansible.builtin.uri:
    url: https://api.github.com/repos/ariga/atlas/releases/latest
    return_content: true
  register: atlas_latest_release_data

- name: Set the release version
  ansible.builtin.set_fact:
    atlas_release_version: "{{ atlas_latest_release_data.json.tag_name if atlas_version == 'latest' else atlas_version }}"

- name: Download and install
  when: atlas_installed_version != atlas_release_version
  block:
    - name: Set the release artifact
      vars:
        arch_name:
          amd: amd64
          arm: arm64
      ansible.builtin.set_fact:
        atlas_release_artifact: "atlas-{{ ansible_facts.system | lower }}-{{ arch }}-{{ atlas_release_version }}"

    - name: Create download temporary directory
      ansible.builtin.tempfile:
        state: directory
        prefix: atlas_
      register: atlas_tempdir

    - name: Download artifact
      ansible.builtin.get_url:
        url: "https://release.ariga.io/atlas/{{ atlas_release_artifact }}"
        dest: "{{ atlas_tempdir.path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x

    - name: Copy binary
      ansible.builtin.copy:
        src: "{{ atlas_tempdir.path }}/{{ atlas_release_artifact }}"
        dest: "{{ atlas_path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x
        remote_src: true

    - name: Cleanup temp files
      ansible.builtin.file:
        path: "{{ atlas_tempdir.path }}"
        state: absent
