---
- name: Include tasks to install atlas
  ansible.builtin.include_tasks: install-atlas.yaml
  when: atlas_state == 'present'

- name: Include tasks to remove atlas
  ansible.builtin.include_tasks: remove-atlas.yaml
  when: atlas_state == 'absent'
