---
# tasks file for mkcert

- name: Get the latest GitHub release data
  ansible.builtin.uri:
    url: https://api.github.com/repos/FiloSottile/mkcert/releases/latest
    return_content: true
  register: mkcert_latest_release_data

- name: Set the latest release version
  ansible.builtin.set_fact:
    mkcert_latest_release_version: "{{ mkcert_latest_release_data.json.tag_name }}"

- name: Set the release artifact
  vars:
    arch_name:
      amd: amd64
      arm: arm64
  ansible.builtin.set_fact:
    mkcert_release_artifact: "mkcert-{{ mkcert_latest_release_version }}-{{ ansible_facts.system | lower }}-{{ arch_name[archs.get(ansible_facts.architecture)] | default(ansible_facts.architecture) }}"

- name: Create download temporary directory
  ansible.builtin.tempfile:
    state: directory
    prefix: mkcert_
  register: mkcert_tempdir

- name: Download artifact
  ansible.builtin.get_url:
    url: "https://github.com/FiloSottile/mkcert/releases/download/{{ mkcert_latest_release_version }}/mkcert-v1.4.4-linux-amd64"
    dest: "{{ mkcert_tempdir.path }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: a+x

- name: Copy binary
  ansible.builtin.copy:
    src: "{{ mkcert_tempdir.path }}/{{ mkcert_release_artifact }}"
    dest: /usr/local/bin/mkcert
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: a+x
    remote_src: true

- name: Cleanup temp files
  ansible.builtin.file:
    path: "{{ mkcert_tempdir.path }}"
    state: absent
