---
# tasks file for mkcert

- name: Include tasks to install mkcert
  ansible.builtin.include_tasks: install-mkcert.yaml
  when: mkcert_state == 'present'

- name: Include tasks to remove mkcert
  ansible.builtin.include_tasks: remove-mkcert.yaml
  when: mkcert_state == 'absent'
