---
# tasks file for multimedia

- name: Swap ffmpeg-free with rpmfusion ffmpeg
  ansible.builtin.command:
    cmd: dnf swap -y --allowerasing ffmpeg-free ffmpeg
  register: swap_result
  changed_when: "'Nothing to do' not in swap_result.stdout"

- name: Update group multimedia codecs
  ansible.builtin.dnf5:
    name:
      - '@multimedia'
      - '@sound-and-video'
    state: latest
    install_weak_deps: false
    exclude:
      - PackageKit-gstreamer-plugin
      - gstreamer1-plugins-bad-free
      - gstreamer1-plugins-ugly-free

- name: Install additional plugins
  ansible.builtin.dnf5:
    name:
      - ffmpegthumbnailer
      - gstreamer1-plugins-bad-freeworld
      - gstreamer1-plugins-ugly
      - libavcodec-freeworld
      - mozilla-openh264
    state: latest
    enablerepo: fedora-cisco-openh264
    allowerasing: true
