---
- name: Setup Fedora Gnome workstation
  hosts: workstation
  connection: local
  vars_files:
    - group_vars/all/vars.yaml
  become: true
  gather_facts: true

  pre_tasks:
    - name: Install and upgrade requirements
      ansible.builtin.command:
        cmd: ansible-galaxy collection install --upgrade -r requirements.yaml
      register: install_reqs
      changed_when: "'is already installed, skipping' not in install_reqs.stdout"

  tasks:
    - name: Include selected roles
      ansible.builtin.include_role:
        name: "{{ role_item }}"
      loop: "{{ roles_selected }}"
      loop_control:
        loop_var: role_item
