---
# defaults file for eza

eza_state: present
eza_version: latest
eza_binary_name: eza
eza_binary_path: "{{ binaries_path | default('/usr/local/bin') }}/{{ eza_binary_name }}"

eza_archs:
  x86_64: x86_64
  amd64: x86_64
  # x86:
  aarch64: aarch64
  arm64: aarch64
  armv9l: aarch64
  armv8l: aarch64
  # armv7l:
  # armv6l:
  # aarch32:
  # s390x:
  # i386:
  # i686:
  # ppc64le:

eza_arch: "{{ eza_archs.get(ansible_facts.architecture) | default(ansible_facts.architecture) }}"

eza_force_download: false

eza_latest_version_url: https://api.github.com/repos/eza-community/eza/releases/latest
eza_base_download_url: https://github.com/eza-community/eza/releases/download
eza_build_lib: gnu
eza_artifact_name: "eza_{{ eza_arch }}-unknown-{{ ansible_facts.system | lower }}-{{ eza_build_lib }}.tar.gz"
eza_artifact_download_url: "{{ eza_base_download_url }}/{{ eza_release_version }}/{{ eza_artifact_name }}"
eza_artifact_basename: "{{ eza_artifact_name | regex_replace('.tar.gz', '') }}"

eza_checksum_algorithm: sha256
eza_checksum_name: "eza_{{ eza_arch }}-unknown-{{ ansible_facts.system | lower }}-{{ eza_build_lib }}.tar.gz"
eza_checksum_url: "{{ eza_base_download_url }}/{{ eza_release_version }}/{{ eza_checksum_name }}"
eza_checksum: "{{ eza_checksum_algorithm }}:{{ eza_checksum_url }}"
