---
# tasks file for delta

- name: Check if installed
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "command -v {{ delta_binary_name }}"
  changed_when: false
  register: delta_installed
  failed_when: delta_installed.rc != 0 and delta_installed.stderr != ""

- name: Get installed version data
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "{{ delta_binary_name }} --version"
  register: delta_installed_version_data
  changed_when: false
  failed_when: "delta_installed_version_data.rc != 0 or (delta_installed_version_data.rc == 0 and 'delta' not in delta_installed_version_data.stdout)"
  when: not delta_installed.failed

- name: Set installed version
  ansible.builtin.set_fact:
    delta_installed_version: "{{ delta_installed_version_data.stdout.split()[1] if not delta_installed_version_data.failed else '' }}"

- name: Get the latest GitHub release data
  ansible.builtin.uri:
    url: https://api.github.com/repos/dandavison/delta/releases/latest
    return_content: true
    headers:
      Authorization: "{{ 'Bearer ' + github_pat if github_pat is defined else omit }}"
  register: delta_latest_release_data

- name: Set the release version
  ansible.builtin.set_fact:
    delta_release_version: "{{ delta_latest_release_data.json.tag_name if delta_version == 'latest' else delta_version }}"

- name: Download and install
  when: delta_installed_version != delta_release_version
  block:
    - name: Set the release artifact
      vars:
        arch_name:
          amd: x86_64
          arm: aarch64
      ansible.builtin.set_fact:
        delta_release_artifact: "delta-{{ delta_release_version }}-{{ arch }}-unknown-{{ ansible_facts.system | lower }}-gnu"

    - name: Create download temporary directory
      ansible.builtin.tempfile:
        state: directory
        prefix: delta_
      register: delta_tempdir

    - name: Unarchive artifact
      ansible.builtin.unarchive:
        src: "https://github.com/dandavison/delta/releases/download/{{ delta_release_version }}/{{ delta_release_artifact }}.tar.gz"
        dest: "{{ delta_tempdir.path }}"
        remote_src: true

    - name: Copy binary
      ansible.builtin.copy:
        src: "{{ delta_tempdir.path }}/{{ delta_release_artifact }}/delta"
        dest: "{{ delta_path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x
        remote_src: true

    - name: Cleanup temp files
      ansible.builtin.file:
        path: "{{ delta_tempdir.path }}"
        state: absent
