---
# tasks file for delta

- name: Check if installed
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "command -v {{ delta_binary_name }}"
  register: delta_installed
  changed_when: false
  failed_when: delta_installed.rc != 0 and delta_installed.stderr != ""

- name: Get installed version data
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "{{ delta_binary_name }} --version"
  register: delta_installed_version_data
  changed_when: false
  failed_when: "delta_installed_version_data.rc != 0 or (delta_installed_version_data.rc == 0 and 'delta' not in delta_installed_version_data.stdout)"
  when: delta_installed.rc == 0

- name: Set installed version
  ansible.builtin.set_fact:
    delta_installed_version: "{{ delta_installed_version_data.stdout.split()[1] if delta_installed.rc == 0 else '' }}"

- name: Get the latest release data
  ansible.builtin.uri:
    url: "{{ delta_latest_version_url }}"
    return_content: true
    headers:
      Authorization: "{{ 'Bearer ' + github_pat if github_pat is defined else omit }}"
  register: delta_latest_release_data
  retries: 3
  delay: 5

- name: Set the release version
  ansible.builtin.set_fact:
    delta_release_version: "{{ delta_latest_release_data.json.tag_name if delta_version == 'latest' else delta_version }}"

- name: Download and install
  when: delta_force_download or delta_installed_version != delta_release_version
  block:
    - name: Create download temporary directory
      ansible.builtin.tempfile:
        state: directory
        prefix: delta_
      register: delta_tempdir

    - name: Unarchive artifact
      ansible.builtin.unarchive:
        src: "{{ delta_artifact_download_url }}"
        dest: "{{ delta_tempdir.path }}"
        remote_src: true

    - name: Copy binary
      ansible.builtin.copy:
        src: "{{ delta_tempdir.path }}/{{ delta_artifact_basename }}/delta"
        dest: "{{ delta_binary_path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x
        remote_src: true

    - name: Cleanup temp files
      ansible.builtin.file:
        path: "{{ delta_tempdir.path }}"
        state: absent
