---
- name: Check if installed
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "command -v {{ lazygit_binary_name }}"
  register: lazygit_installed
  changed_when: false
  failed_when: lazygit_installed.rc != 0 and lazygit_installed.stderr != ""

- name: Get installed version data
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "{{ lazygit_binary_name }} --version"
  register: lazygit_installed_version_data
  changed_when: false
  failed_when: "lazygit_installed_version_data.rc != 0 or (lazygit_installed_version_data.rc == 0 and 'version' not in lazygit_installed_version_data.stdout)"
  when: lazygit_installed.rc == 0

- name: Set installed version
  ansible.builtin.set_fact:
    lazygit_installed_version: "{{ 'v' + lazygit_installed_version_data.stdout.split(',')[3].split('=')[1] if lazygit_installed.rc == 0 else '' }}" # noqa yaml[line-length]

- name: Get the latest release data
  ansible.builtin.uri:
    url: "{{ lazygit_latest_version_url }}"
    return_content: true
    headers:
      Authorization: "{{ 'Bearer ' + github_pat if github_pat is defined else omit }}"
  register: lazygit_latest_release_data
  retries: 3
  delay: 5

- name: Set the release version
  ansible.builtin.set_fact:
    lazygit_release_version: "{{ lazygit_latest_release_data.json.tag_name if lazygit_version == 'latest' else lazygit_version }}"

- name: Download and install
  when: lazygit_force_download or lazygit_installed_version != lazygit_release_version
  block:
    - name: Create download temporary directory
      ansible.builtin.tempfile:
        state: directory
        prefix: lazygit_
      register: lazygit_tempdir

    - name: Download checksums
      ansible.builtin.get_url:
        url: "{{ lazygit_checksum_url }}"
        dest: "{{ lazygit_tempdir.path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0644"
      register: downloaded_checksums

    - name: Get checksum text content
      ansible.builtin.slurp:
        src: "{{ downloaded_checksums.dest }}"
      register: checksums_data

    - name: Get sha256 text content
      ansible.builtin.set_fact:
        sha256_text: "{{ checksums_data.content | b64decode | trim }}"

    - name: Get search word rhs
      ansible.builtin.set_fact:
        search_word_rhs: "{{ lazygit_artifact_name }}"

    - name: Extract checksum
      ansible.builtin.set_fact:
        lazygit_checksum: "{{ lazygit_checksum_algorithm }}:{{ sha256_text | regex_search('([a-f0-9]{64})\\s+.*' ~ search_word_rhs) | split | first }}"

    - name: Download artifact
      ansible.builtin.get_url:
        url: "{{ lazygit_artifact_download_url }}"
        dest: "{{ lazygit_tempdir.path }}"
        checksum: "{{ lazygit_checksum }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x
      register: downloaded_artifact

    - name: Unarchive artifact
      ansible.builtin.unarchive:
        src: "{{ downloaded_artifact.dest }}"
        dest: "{{ lazygit_tempdir.path }}"
        remote_src: true

    - name: Copy binary
      ansible.builtin.copy:
        src: "{{ lazygit_tempdir.path }}/lazygit"
        dest: "{{ lazygit_binary_path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x
        remote_src: true

    - name: Cleanup temp files
      ansible.builtin.file:
        path: "{{ lazygit_tempdir.path }}"
        state: absent
