---
- name: Check if installed
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "command -v {{ lazygit_binary_name }}"
  register: lazygit_installed
  changed_when: false
  failed_when: lazygit_installed.rc != 0 and lazygit_installed.stderr != ""

- name: Get installed version data
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "{{ lazygit_binary_name }} --version"
  register: lazygit_installed_version_data
  changed_when: false
  failed_when: "lazygit_installed_version_data.rc != 0 or (lazygit_installed_version_data.rc == 0 and 'version' not in lazygit_installed_version_data.stdout)"
  when: lazygit_installed.rc == 0

- name: Set installed version
  ansible.builtin.set_fact:
    lazygit_installed_version: "{{ 'v' + lazygit_installed_version_data.stdout.split(',')[3].split('=')[1] if lazygit_installed.rc == 0 else '' }}" # noqa yaml[line-length]

- name: Get the latest release data
  ansible.builtin.uri:
    url: https://api.github.com/repos/jesseduffield/lazygit/releases/latest
    return_content: true
    headers:
      Authorization: "{{ 'Bearer ' + github_pat if github_pat is defined else omit }}"
  register: lazygit_latest_release_data

- name: Set the release version
  ansible.builtin.set_fact:
    lazygit_release_version: "{{ lazygit_latest_release_data.json.tag_name if lazygit_version == 'latest' else lazygit_version }}"

- name: Download and install
  when: lazygit_installed_version != lazygit_release_version
  block:
    - name: Set the release artifact
      vars:
        arch_name:
          amd: x86_64
          arm: arm64
      ansible.builtin.set_fact:
        lazygit_release_artifact: "lazygit_{{ lazygit_release_version[1:] }}_{{ ansible_facts.system }}_{{ arch }}"

    - name: Create download temporary directory
      ansible.builtin.tempfile:
        state: directory
        prefix: lazygit_
      register: lazygit_tempdir

    - name: Unarchive artifact
      ansible.builtin.unarchive:
        src: "https://github.com/jesseduffield/lazygit/releases/download/{{ lazygit_release_version }}/{{ lazygit_release_artifact }}.tar.gz"
        dest: "{{ lazygit_tempdir.path }}"
        remote_src: true

    - name: Copy binary
      ansible.builtin.copy:
        src: "{{ lazygit_tempdir.path }}/lazygit"
        dest: "{{ lazygit_binary_path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x
        remote_src: true

    - name: Cleanup temp files
      ansible.builtin.file:
        path: "{{ lazygit_tempdir.path }}"
        state: absent
