---
# tasks file for lazygit

- name: Include tasks to install lazygit
  ansible.builtin.include_tasks: install-lazygit.yaml
  when: lazygit_state == 'present'

- name: Include tasks to remove lazygit
  ansible.builtin.include_tasks: remove-lazygit.yaml
  when: lazygit_state == 'absent'
