---
# tasks file for extension-manager

- name: Install Extension Manager
  community.general.flatpak:
    name: com.mattjakeman.ExtensionManager
    state: latest

- name: Get the gnome shell version
  ansible.builtin.command: gnome-shell --version
  changed_when: false
  register: gnome_shell_version_data

- name: Get extensions info data
  ansible.builtin.uri:
    url: "https://extensions.gnome.org/extension-info/?pk={{ item.id }}&shell_version={{ gnome_shell_version_data.stdout.split()[2] | int }}"
    return_content: true
  register: gnome_extensions_info
  loop: "{{ gnome_extensions }}"

- name: Ensure individual extension directories exist
  ansible.builtin.file:
    path: "/{{ gnome_extensions_dir }}/{{ item.json.uuid }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop: "{{ gnome_extensions_info.results }}"

- name: Unarchive remote extensions
  ansible.builtin.unarchive:
    src: "{{ gnome_extensions_url }}{{ item.json.download_url }}"
    dest: "/{{ gnome_extensions_dir }}/{{ item.json.uuid }}"
    remote_src: true
  loop: "{{ gnome_extensions_info.results }}"

- name: Enable extensions
  ansible.builtin.command: "gnome-shell-extension-tool {{ '-e' if (gnome_extensions | selectattr('id', '==', item.json.pk) | first).state == 'present' else '-d' }} {{ item.json.uuid }}"
  changed_when: false
  loop: "{{ gnome_extensions_info.results }}"
