---
all:
  hosts:
    workstation:
      ansible_host: 127.0.0.1
      ansible_user: "{{ username }}"
      ansible_connection: local
      ansible_ssh_private_key_file: "/home/{{ username }}/.ssh/id_ed25519"
      ansible_become_method: sudo
      ansible_become_password: "{{ sudo_password }}"
