---
# tasks file for helix

- name: Include tasks to install helix
  ansible.builtin.include_tasks: install-helix.yaml
  when: helix_state == 'present'

- name: Include tasks to remove helix
  ansible.builtin.include_tasks: remove-helix.yaml
  when: helix_state == 'absent'
