---
# tasks file for zram

- name: Copy zram-generator.conf
  ansible.builtin.template:
    src: zram-generator.conf.j2
    dest: /etc/systemd/system/zram-generator.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd daemon
