---
# tasks file for devspace

- name: Include tasks to install devspace
  ansible.builtin.include_tasks: install-devspace.yaml
  when: devspace_state == 'present'

- name: Include tasks to remove devspace
  ansible.builtin.include_tasks: remove-devspace.yaml
  when: devspace_state == 'absent'
