---
# tasks file for vscode

- name: Add repository
  ansible.builtin.yum_repository:
    name: vscode
    description: VSCode yum repository
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: true
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Install VSCode
  ansible.builtin.dnf:
    name: code
    state: latest
