---
# defaults file for gh

gh_state: present
gh_version: latest
gh_binary_name: gh
gh_binary_path: "{{ binaries_path }}/{{ gh_binary_name }}"

gh_archs:
  x86_64: amd64
  amd64: amd64
  # x86:
  aarch64: arm64
  arm64: arm64
  armv9l: arm64
  armv8l: arm64
  # armv7l:
  # armv6l:
  # aarch32:
  # s390x:
  # i386:
  # i686:
  # ppc64le:

gh_arch: "{{ gh_archs.get(ansible_facts.architecture) | default(ansible_facts.architecture) }}"

gh_force_download: false

gh_latest_version_url: https://api.github.com/repos/cli/cli/releases/latest
gh_base_download_url: https://github.com/cli/cli/releases/download
gh_artifact_name: "gh_{{ gh_release_version[1:] }}_{{ ansible_facts.system | lower }}_{{ gh_arch }}.tar.gz"
gh_artifact_download_url: "{{ gh_base_download_url }}/{{ gh_release_version }}/{{ gh_artifact_name }}"
gh_artifact_basename: "{{ gh_artifact_name | regex_replace('.tar.gz', '') }}"

gh_checksum_algorithm: sha256
gh_checksum_name: "gh_{{ gh_release_version[1:] }}_checksums.txt"
gh_checksum_url: "{{ gh_base_download_url }}/{{ gh_release_version }}/{{ gh_checksum_name }}"
gh_checksum: "{{ gh_checksum_algorithm }}:{{ gh_checksum_url }}"
