---
# tasks file for glow

- name: Get the latest GitHub release data
  ansible.builtin.uri:
    url: https://api.github.com/repos/charmbracelet/glow/releases/latest
    return_content: true
  register: glow_latest_release_data

- name: Set the latest release version
  ansible.builtin.set_fact:
    glow_latest_release_version: "{{ glow_latest_release_data.json.tag_name }}"

- name: Set the release artifact
  vars:
    arch_name:
      amd: x86_64
      arm: arm64
  ansible.builtin.set_fact:
    glow_release_artifact: "glow_{{ glow_latest_release_version[1:] }}_{{ ansible_facts.system }}_{{ arch_name[archs.get(ansible_facts.architecture)] | default(ansible_facts.architecture) }}"

- name: Create download temporary directory
  ansible.builtin.tempfile:
    state: directory
    prefix: glow_
  register: glow_tempdir

- name: Unarchive artifact
  ansible.builtin.unarchive:
    src: "https://github.com/charmbracelet/glow/releases/download/{{ glow_latest_release_version }}/{{ glow_release_artifact }}.tar.gz"
    dest: "{{ glow_tempdir.path }}"
    remote_src: true

- name: Copy binary
  ansible.builtin.copy:
    src: "{{ glow_tempdir.path }}/{{ glow_release_artifact }}/glow"
    dest: /usr/local/bin
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: a+x
    remote_src: true

- name: Cleanup temp files
  ansible.builtin.file:
    path: "{{ glow_tempdir.path }}"
    state: absent
