---
# tasks file for glow

- name: Include tasks to install glow
  ansible.builtin.include_tasks: install-glow.yaml
  when: glow_state == 'present'

- name: Include tasks to remove glow
  ansible.builtin.include_tasks: remove-glow.yaml
  when: glow_state == 'absent'
