---
# tasks file for protoc

- name: Include tasks to install protoc
  ansible.builtin.include_tasks: install-protoc.yaml
  when: protoc_state == 'present'

- name: Include tasks to remove protoc
  ansible.builtin.include_tasks: remove-protoc.yaml
  when: protoc_state == 'absent'
