---
# handlers file for grub

- name: Regenerate GRUB configuration file # noqa no-changed-when
  ansible.builtin.command: grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg
  # Not sure if i can use `creates` here, because it might not be run if grub.cfg already exists, but new generated cfg is different
