---
# tasks file for rclone

- name: Include tasks to install rclone
  ansible.builtin.include_tasks: install-rclone.yaml
  when: rclone_state == 'present'

- name: Include tasks to remove rclone
  ansible.builtin.include_tasks: remove-rclone.yaml
  when: rclone_state == 'absent'
