---
# tasks file for xh

- name: Include tasks to install xh
  ansible.builtin.include_tasks: install-xh.yaml
  when: xh_state == 'present'

- name: Include tasks to remove xh
  ansible.builtin.include_tasks: remove-xh.yaml
  when: xh_state == 'absent'
