---
# defaults file for kubectl

kubectl_state: present
kubectl_version: latest
kubectl_binary_name: kubectl
kubectl_binary_path: "{{ binaries_path }}/{{ kubectl_binary_name }}"

kubectl_archs:
  x86_64: amd64
  amd64: amd64
  # x86:
  aarch64: arm64
  arm64: arm64
  armv9l: arm64
  armv8l: arm64
  # armv7l:
  # armv6l:
  # aarch32:
  # s390x:
  # i386:
  # i686:
  # ppc64le:

kubectl_arch: "{{ kubectl_archs.get(ansible_facts.architecture) | default(ansible_facts.architecture) }}"

kubectl_force_download: false

kubectl_latest_version_url: https://dl.k8s.io/release/stable.txt
kubectl_base_download_url: https://dl.k8s.io/release
kubectl_build_lib: gnu
kubectl_artifact_name: "{{ kubectl_release_version }}/bin/{{ ansible_facts.system | lower }}/{{ kubectl_arch }}/kubectl"
kubectl_artifact_download_url: "{{ kubectl_base_download_url }}/{{ kubectl_artifact_name }}"
kubectl_artifact_basename: "{{ kubectl_artifact_name }}"

kubectl_checksum_algorithm: sha256
kubectl_checksum_name: "{{ kubectl_release_version }}/bin/{{ ansible_facts.system | lower }}/{{ kubectl_arch }}/kubectl.sha256"
kubectl_checksum_url: "{{ kubectl_base_download_url }}/{{ kubectl_checksum_name }}"
kubectl_checksum: "{{ kubectl_checksum_algorithm }}:{{ kubectl_checksum_url }}"
