---
# tasks file for nautilus

- name: Ensure Nautilus Templates directory exists
  ansible.builtin.file:
    path: "/home/{{ username }}/Templates"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
    modification_time: preserve
    access_time: preserve

- name: Copy Nautilus templates
  ansible.builtin.copy:
    src: Templates/
    dest: "/home/{{ username }}/Templates"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0644"
