---
# tasks file for restic

- name: Include tasks to install restic
  ansible.builtin.include_tasks: install-restic.yaml
  when: restic_state == 'present'

- name: Include tasks to remove restic
  ansible.builtin.include_tasks: remove-restic.yaml
  when: restic_state == 'absent'
