---
- name: Check if installed
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "command -v {{ k3d_binary_name }}"
  register: k3d_installed
  changed_when: false
  failed_when: k3d_installed.rc != 0 and k3d_installed.stderr != ""

- name: Get installed version data
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "{{ k3d_binary_name }} --version"
  register: k3d_installed_version_data
  changed_when: false
  failed_when: "k3d_installed_version_data.rc != 0 or (k3d_installed_version_data.rc == 0 and 'k3d' not in k3d_installed_version_data.stdout)"
  when: k3d_installed.rc == 0

- name: Set installed version
  ansible.builtin.set_fact:
    k3d_installed_version: "{{ k3d_installed_version_data.stdout_lines[0].split()[2] if k3d_installed.rc == 0 else '' }}"

- name: Get the latest release data
  ansible.builtin.uri:
    url: "{{ k3d_latest_version_url }}"
    return_content: true
    headers:
      Authorization: "{{ 'Bearer ' + github_pat if github_pat is defined else omit }}"
  register: k3d_latest_release_data
  retries: 3
  delay: 5

- name: Set the release version
  ansible.builtin.set_fact:
    k3d_release_version: "{{ k3d_latest_release_data.json.tag_name if k3d_version == 'latest' else k3d_version }}"

- name: Download and install
  when: k3d_force_download or k3d_installed_version != k3d_release_version
  block:
    - name: Create download temporary directory
      ansible.builtin.tempfile:
        state: directory
        prefix: k3d_
      register: k3d_tempdir

    - name: Download checksums
      ansible.builtin.get_url:
        url: "{{ k3d_checksum_url }}"
        dest: "{{ k3d_tempdir.path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0644"
      register: downloaded_checksums

    - name: Get checksum text content
      ansible.builtin.slurp:
        src: "{{ downloaded_checksums.dest }}"
      register: checksums_data

    - name: Get sha256 text content
      ansible.builtin.set_fact:
        sha256_text: "{{ checksums_data.content | b64decode | trim }}"

    - name: Get search word rhs
      ansible.builtin.set_fact:
        search_word_rhs: "_dist/{{ k3d_artifact_name }}"

    - name: Extract checksum
      ansible.builtin.set_fact:
        k3d_checksum: "{{ k3d_checksum_algorithm }}:{{ sha256_text | regex_search('([a-f0-9]{64})\\s+.*' ~ search_word_rhs) | split | first }}"

    - name: Download artifact
      ansible.builtin.get_url:
        url: "{{ k3d_artifact_download_url }}"
        dest: "{{ k3d_tempdir.path }}"
        checksum: "{{ k3d_checksum }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x
      register: downloaded_artifact

    - name: Copy binary
      ansible.builtin.copy:
        src: "{{ k3d_tempdir.path }}/{{ k3d_artifact_basename }}"
        dest: "{{ k3d_binary_path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x
        remote_src: true

    - name: Cleanup temp files
      ansible.builtin.file:
        path: "{{ k3d_tempdir.path }}"
        state: absent
