---
# tasks file for k3d

- name: Include tasks to install k3d
  ansible.builtin.include_tasks: install-k3d.yaml
  when: k3d_state == 'present'

- name: Include tasks to remove k3d
  ansible.builtin.include_tasks: remove-k3d.yaml
  when: k3d_state == 'absent'
