---
# tasks file for python

- name: Install python3 and pip
  ansible.builtin.dnf5:
    name:
      - python3
      - python3-pip
      - pipx
    state: "{{ python_state }}"

- name: Ensure python2 does not exist
  ansible.builtin.dnf5:
    name: python2
    state: absent
