---
# tasks file for nvidia

- name: Install Nvidia GPU drivers
  ansible.builtin.dnf:
    name:
      - mesa-vulkan-drivers
      - vulkan
      - vulkan-tools
      - akmod-nvidia
      - xorg-x11-drv-nvidia
      - xorg-x11-drv-nvidia-cuda
      - intel-media-driver
    state: latest
    update_cache: true

- name: Check the kernel module version
  ansible.builtin.command:
    cmd: modinfo -F version nvidia
  register: kernel_module_status
  changed_when: false
  failed_when: >
    not (kernel_module_status.stdout | regex_search('^\d+\.\d+\.\d+$') or 'Module nvidia not found' in kernel_module_status.stdout)

- name: Display the kernel module status
  ansible.builtin.debug:
    msg: "{{ kernel_module_status.stdout }}"
  failed_when: false

- name: Wait for the kernel module to be built
  ansible.builtin.pause:
    seconds: 30
  when: "'Module nvidia not found' in kernel_module_status.stdout"
  failed_when: false

- name: Check if a reboot is required
  ansible.builtin.command:
    cmd: dnf needs-restarting -r -s
  register: reboot_required
  changed_when: "'Reboot should not be necessary' not in reboot_required.stdout"
  failed_when: false
  notify: Reboot machine
