---
# defaults file for mkcert

mkcert_state: present
mkcert_version: latest
mkcert_binary_name: mkcert
mkcert_binary_path: "{{ binaries_path }}/{{ mkcert_binary_name }}"

mkcert_archs:
  x86_64: amd64
  amd64: amd64
  # x86:
  aarch64: arm64
  arm64: arm64
  armv9l: arm64
  armv8l: arm64
  # armv7l:
  # armv6l:
  # aarch32:
  # s390x:
  # i386:
  # i686:
  # ppc64le:

mkcert_arch: "{{ mkcert_archs.get(ansible_facts.architecture) | default(ansible_facts.architecture) }}"

mkcert_force_download: false

mkcert_latest_version_url: https://api.github.com/repos/FiloSottile/mkcert/releases/latest
mkcert_base_download_url: https://github.com/FiloSottile/mkcert/releases/download
mkcert_artifact_name: "mkcert-{{ mkcert_release_version }}-{{ ansible_facts.system | lower }}-{{ mkcert_arch }}"
mkcert_artifact_download_url: "{{ mkcert_base_download_url }}/{{ mkcert_release_version }}/{{ mkcert_artifact_name }}"
mkcert_artifact_basename: "{{ mkcert_artifact_name }}"
