---
# defaults file for node

node_state: present
node_version: latest
node_binary_name: node
node_binary_path: "{{ binaries_path }}/{{ node_binary_name }}"
node_corepack_binary_name: corepack
node_corepack_binary_path: "{{ binaries_path }}/{{ node_corepack_binary_name }}"
node_npm_binary_name: npm
node_npm_binary_path: "{{ binaries_path }}/{{ node_npm_binary_name }}"
node_npx_binary_name: npx
node_npx_binary_path: "{{ binaries_path }}/{{ node_npx_binary_name }}"
node_npm_global_dir: /usr/local/lib/npm-global

node_global_packages:
  - name: "vscode-langservers-extracted"
  - name: "@ansible/ansible-language-server"
  - name: "dockerfile-language-server-nodejs"
  - name: "@microsoft/compose-language-service"
  - name: "typescript"
  - name: "typescript-language-server"
  - name: "svelte-language-server"
  - name: "typescript-svelte-plugin"
  - name: "yaml-language-server"
    version: "next"
