---
# tasks file for flatpak

- name: Install Flatpak
  ansible.builtin.dnf5:
    name: flatpak
    state: latest

- name: Remove fedora flatpak repo
  community.general.flatpak_remote:
    name: fedora
    state: absent
    enabled: false

- name: Add Flathub repository
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    state: present
    enabled: true

- name: Update Flatpak appstream metadata
  ansible.builtin.command:
    cmd: flatpak update --appstream
  changed_when: false
