---
# tasks file for git-delta

- name: Get the latest GitHub release data
  ansible.builtin.uri:
    url: https://api.github.com/repos/dandavison/delta/releases/latest
    return_content: true
  register: delta_latest_release_data

- name: Set the latest release version
  ansible.builtin.set_fact:
    delta_latest_release_version: "{{ delta_latest_release_data.json.tag_name }}"

- name: Set the release artifact
  vars:
    arch_name:
      amd: x86_64
      arm: aarch64
  ansible.builtin.set_fact:
    delta_release_artifact: "delta-{{ delta_latest_release_version }}-{{ arch_name[archs.get(ansible_facts.architecture)] | default(ansible_facts.architecture) }}-unknown-{{ ansible_facts.system | lower }}-gnu"

- name: Create download temporary directory
  ansible.builtin.tempfile:
    state: directory
    prefix: delta_
  register: delta_tempdir

- name: Unarchive artifact
  ansible.builtin.unarchive:
    src: "https://github.com/dandavison/delta/releases/download/{{ delta_latest_release_version }}/{{ delta_release_artifact }}.tar.gz"
    dest: "{{ delta_tempdir.path }}"
    remote_src: true

- name: Copy binary
  ansible.builtin.copy:
    src: "{{ delta_tempdir.path }}/{{ delta_release_artifact }}/delta"
    dest: /usr/local/bin
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: a+x
    remote_src: true

- name: Cleanup temp files
  ansible.builtin.file:
    path: "{{ delta_tempdir.path }}"
    state: absent
