---
- name: Check if installed
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "command -v {{ zed_binary_name }}"
  register: zed_installed
  changed_when: false
  failed_when: zed_installed.rc != 0 and zed_installed.stderr != ""

- name: Get installed version data
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "{{ zed_binary_name }} --version"
  register: zed_installed_version_data
  changed_when: false
  failed_when: "zed_installed_version_data.rc != 0 or (zed_installed_version_data.rc == 0 and 'zed' not in zed_installed_version_data.stdout)"
  when: zed_installed.rc == 0

- name: Set installed version
  ansible.builtin.set_fact:
    zed_installed_version: "{{ 'v' + zed_installed_version_data.stdout.split()[1] if zed_installed.rc == 0 else '' }}"

- name: Get the latest release data
  ansible.builtin.uri:
    url: https://api.github.com/repos/zed-industries/zed/releases/latest
    return_content: true
    headers:
      Authorization: "{{ 'Bearer ' + github_pat if github_pat is defined else omit }}"
  register: zed_latest_release_data
  retries: 3
  delay: 5

- name: Set the release version
  ansible.builtin.set_fact:
    zed_release_version: "{{ zed_latest_release_data.json.tag_name if zed_version == 'latest' else zed_version }}"

- name: Download and install
  when: zed_installed_version != zed_release_version
  block:
    - name: Set the release artifact
      vars:
        arch_name:
          amd: x86_64
          arm: aarch64
      ansible.builtin.set_fact:
        zed_release_artifact: "zed-{{ ansible_facts.system | lower }}-{{ arch }}"

    - name: Create download temporary directory
      ansible.builtin.tempfile:
        state: directory
        prefix: zed_
      register: zed_tempdir

    - name: Unarchive artifact
      ansible.builtin.unarchive:
        src: "https://github.com/zed-industries/zed/releases/download/{{ zed_release_version }}/{{ zed_release_artifact }}.tar.gz"
        dest: "{{ zed_tempdir.path }}"
        remote_src: true

    - name: Copy binary
      ansible.builtin.copy:
        src: "{{ zed_tempdir.path }}/zed.app/bin/zed"
        dest: "{{ zed_binary_path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x
        remote_src: true

    - name: Copy .so files if they don't exist
      ansible.builtin.copy:
        src: "{{ zed_tempdir.path }}/zed.app/lib/"
        dest: "/usr/lib64"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0755"
        remote_src: true
        force: false

    - name: Copy libexec
      ansible.builtin.copy:
        src: "{{ zed_tempdir.path }}/zed.app/libexec/zed-editor"
        dest: /usr/local/libexec
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x
        remote_src: true

    - name: Copy desktop file
      ansible.builtin.copy:
        src: "{{ zed_tempdir.path }}/zed.app/share/applications/zed.desktop"
        dest: /usr/local/share/applications/zed.desktop
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0644"
        remote_src: true

    - name: Ensure icons directories exist
      ansible.builtin.file:
        path: "/usr/local/share/icons/hicolor/{{ item }}/apps"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0755"
      loop:
        - "512x512"
        - "1024x1024"

    - name: Copy icons
      ansible.builtin.copy:
        src: "{{ zed_tempdir.path }}/zed.app/share/icons/hicolor/{{ item }}/apps/zed.png"
        dest: /usr/local/share/icons/hicolor/{{ item }}/apps/zed.png
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0644"
        remote_src: true
      loop:
        - "512x512"
        - "1024x1024"

    - name: Cleanup temp files
      ansible.builtin.file:
        path: "{{ zed_tempdir.path }}"
        state: absent
