---
# tasks file for zed

- name: Get the latest GitHub release data
  ansible.builtin.uri:
    url: https://api.github.com/repos/zed-industries/zed/releases/latest
    return_content: true
  register: zed_latest_release_data

- name: Set the latest release version
  ansible.builtin.set_fact:
    zed_latest_release_version: "{{ zed_latest_release_data.json.tag_name }}"

- name: Set the release artifact
  vars:
    arch_name:
      amd: x86_64
      arm: aarch64
  ansible.builtin.set_fact:
    zed_release_artifact: "zed-{{ ansible_facts.system | lower }}-{{ arch_name[archs.get(ansible_facts.architecture)] | default(ansible_facts.architecture) }}"

- name: Create download temporary directory
  ansible.builtin.tempfile:
    state: directory
    prefix: zed_
  register: zed_tempdir

- name: Unarchive artifact
  ansible.builtin.unarchive:
    src: "https://github.com/zed-industries/zed/releases/download/{{ zed_latest_release_version }}/{{ zed_release_artifact }}.tar.gz"
    dest: "{{ zed_tempdir.path }}"
    remote_src: true

- name: Copy binary
  ansible.builtin.copy:
    src: "{{ zed_tempdir.path }}/zed.app/bin/zed"
    dest: /usr/local/bin
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: a+x
    remote_src: true

- name: Cleanup temp files
  ansible.builtin.file:
    path: "{{ zed_tempdir.path }}"
    state: absent
