---
# tasks file for zed

- name: Include tasks to install zed
  ansible.builtin.include_tasks: install-zed.yaml
  when: zed_state == 'present'

- name: Include tasks to remove zed
  ansible.builtin.include_tasks: remove-zed.yaml
  when: zed_state == 'absent'
