---
- name: Ensure removed
  ansible.builtin.file:
    path: "{{ zed_path }}"
    state: absent
  loop:
    - "{{ zed_path }}"
    - /usr/local/libexec/zed-editor
    - /usr/local/share/applications/zed.desktop
    - /usr/local/share/icons/hicolor/512x512/apps/zed.png
    - /usr/local/share/icons/hicolor/1024x1024/apps/zed.png
