---
- name: Check if installed
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "command -v {{ kustomize_binary_name }}"
  register: kustomize_installed
  changed_when: false
  failed_when: kustomize_installed.rc != 0 and kustomize_installed.stderr != ""

- name: Get installed version data
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "{{ kustomize_binary_name }} version"
  register: kustomize_installed_version_data
  changed_when: false
  failed_when: >
    kustomize_installed_version_data.rc != 0 or not (kustomize_installed_version_data.stdout | regex_search('^v\d+\.\d+\.\d+$'))
  when: kustomize_installed.rc == 0

- name: Set installed version
  ansible.builtin.set_fact:
    kustomize_installed_version: "{{ kustomize_installed_version_data.stdout if kustomize_installed.rc == 0 else '' }}"

- name: Get the latest release data
  ansible.builtin.uri:
    url: https://api.github.com/repos/kubernetes-sigs/kustomize/releases/latest
    return_content: true
    headers:
      Authorization: "{{ 'Bearer ' + github_pat if github_pat is defined else omit }}"
  register: kustomize_latest_release_data
  retries: 3
  delay: 5

- name: Set the release version
  ansible.builtin.set_fact:
    kustomize_release_version: "{{ kustomize_latest_release_data.json.tag_name.split('/')[1] if kustomize_version == 'latest' else kustomize_version }}"

- name: Download and install
  when: kustomize_installed_version != kustomize_release_version
  block:
    - name: Set the release artifact
      vars:
        arch_name:
          amd: amd64
          arm: arm64
      ansible.builtin.set_fact:
        kustomize_release_artifact: "kustomize_{{ kustomize_release_version }}_{{ ansible_facts.system | lower }}_{{ arch }}"

    - name: Create download temporary directory
      ansible.builtin.tempfile:
        state: directory
        prefix: kustomize_
      register: kustomize_tempdir

    - name: Unarchive artifact
      ansible.builtin.unarchive:
        src: "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/{{ kustomize_release_version }}/{{ kustomize_release_artifact }}.tar.gz"
        dest: "{{ kustomize_tempdir.path }}"
        remote_src: true

    - name: Copy binary
      ansible.builtin.copy:
        src: "{{ kustomize_tempdir.path }}/kustomize"
        dest: "{{ kustomize_binary_path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x
        remote_src: true

    - name: Cleanup temp files
      ansible.builtin.file:
        path: "{{ kustomize_tempdir.path }}"
        state: absent
