---
# tasks file for kustomize

- name: Include tasks to install kustomize
  ansible.builtin.include_tasks: install-kustomize.yaml
  when: kustomize_state == 'present'

- name: Include tasks to remove kustomize
  ansible.builtin.include_tasks: remove-kustomize.yaml
  when: kustomize_state == 'absent'
