---
# tasks file for kustomize

- name: Get the latest GitHub release data
  ansible.builtin.uri:
    url: https://api.github.com/repos/kubernetes-sigs/kustomize/releases/latest
    return_content: true
  register: kustomize_latest_release_data

- name: Set the latest release version
  ansible.builtin.set_fact:
    kustomize_latest_release_version: "{{ kustomize_latest_release_data.json.tag_name.split('/')[1] }}"

- name: Set the release artifact
  vars:
    arch_name:
      amd: amd64
      arm: arm64
  ansible.builtin.set_fact:
    kustomize_release_artifact: "kustomize_{{ kustomize_latest_release_version }}_{{ ansible_facts.system | lower }}_{{ arch_name[archs.get(ansible_facts.architecture)] | default(ansible_facts.architecture) }}"

- name: Create download temporary directory
  ansible.builtin.tempfile:
    state: directory
    prefix: kustomize_
  register: kustomize_tempdir

- name: Unarchive artifact
  ansible.builtin.unarchive:
    src: "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/{{ kustomize_latest_release_version }}/{{ kustomize_release_artifact }}.tar.gz"
    dest: "{{ kustomize_tempdir.path }}"
    remote_src: true

- name: Copy binary
  ansible.builtin.copy:
    src: "{{ kustomize_tempdir.path }}/kustomize"
    dest: /usr/local/bin/
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: a+x
    remote_src: true

- name: Cleanup temp files
  ansible.builtin.file:
    path: "{{ kustomize_tempdir.path }}"
    state: absent
