---
# tasks file for kubectl

- name: Include tasks to install kubectl
  ansible.builtin.include_tasks: install-kubectl.yaml
  when: kubectl_state == 'present'

- name: Include tasks to remove kubectl
  ansible.builtin.include_tasks: remove-kubectl.yaml
  when: kubectl_state == 'absent'
