---
# tasks file for kitty

- name: Include tasks to install kitty
  ansible.builtin.include_tasks: install-kitty.yaml
  when: kitty_state == 'present'

- name: Include tasks to remove kitty
  ansible.builtin.include_tasks: remove-kitty.yaml
  when: kitty_state == 'absent'
