---
- name: Check if installed
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "command -v {{ kubens_binary_name }}"
  register: kubens_installed
  changed_when: false
  failed_when: kubens_installed.rc != 0 and kubens_installed.stderr != ""

- name: Get installed version data
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "{{ kubens_binary_name }} --version"
  register: kubens_installed_version_data
  changed_when: false
  failed_when: >
    kubens_installed_version_data.rc != 0 or not (kubens_installed_version_data.stdout | regex_search('^\d+\.\d+\.\d+$'))
  when: kubens_installed.rc == 0

- name: Set installed version
  ansible.builtin.set_fact:
    kubens_installed_version: "{{ 'v' + kubens_installed_version_data.stdout if kubens_installed.rc == 0 else '' }}"

- name: Get the latest release data
  ansible.builtin.uri:
    url: https://api.github.com/repos/ahmetb/kubectx/releases/latest
    return_content: true
    headers:
      Authorization: "{{ 'Bearer ' + github_pat if github_pat is defined else omit }}"
  register: kubens_latest_release_data

- name: Set the release version
  ansible.builtin.set_fact:
    kubens_release_version: "{{ kubens_latest_release_data.json.tag_name if kubens_version == 'latest' else kubens_version }}"

- name: Download and install
  when: kubens_installed_version != kubens_release_version
  block:
    - name: Set the release artifact
      vars:
        arch_name:
          amd: x86_64
          arm: arm64
      ansible.builtin.set_fact:
        kubens_release_artifact: "kubens_{{ kubens_latest_release_version }}_{{ ansible_facts.system | lower }}_{{ arch }}"

    - name: Create download temporary directory
      ansible.builtin.tempfile:
        state: directory
        prefix: kubens_
      register: kubens_tempdir

    - name: Unarchive artifact
      ansible.builtin.unarchive:
        src: "https://github.com/ahmetb/kubectx/releases/download/{{ kubens_latest_release_version }}/{{ kubens_release_artifact }}.tar.gz"
        dest: "{{ kubens_tempdir.path }}"
        remote_src: true

    - name: Copy binary
      ansible.builtin.copy:
        src: "{{ kubens_tempdir.path }}/kubens"
        dest: "{{ kubens_binary_path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x
        remote_src: true

    - name: Cleanup temp files
      ansible.builtin.file:
        path: "{{ kubens_tempdir.path }}"
        state: absent
