---
# tasks file for kubens

- name: Include tasks to install kubens
  ansible.builtin.include_tasks: install-kubens.yaml
  when: kubens_state == 'present'

- name: Include tasks to remove kubens
  ansible.builtin.include_tasks: remove-kubens.yaml
  when: kubens_state == 'absent'
