---
# tasks file for gnome

- name: Copy user account image
  ansible.builtin.copy:
    src: account_image/image
    dest: "/var/lib/AccountsService/icons/{{ username }}"
    owner: root
    group: root
    mode: "0644"

- name: Install common gnome apps
  ansible.builtin.dnf:
    name: "{{ gnome_apps }}"
    state: latest

- name: Create dconf-all temporary directory
  ansible.builtin.tempfile:
    state: directory
    prefix: dconf_
  register: dconf_tempdir

- name: Copy dconf-all settings
  ansible.builtin.copy:
    src: dconf-all
    dest: "{{ dconf_tempdir.path }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0644"

- name: Load all dconf settings
  ansible.builtin.shell: "set -o pipefail; dconf load -f / < {{ dconf_tempdir.path }}/dconf-all"
  changed_when: true

- name: Update dconf db
  ansible.builtin.command: dconf update
  changed_when: true

- name: Cleanup temp files
  ansible.builtin.file:
    path: "{{ dconf_tempdir.path }}"
    state: absent
