---
# tasks file for kubectx

- name: Include tasks to install kubectx
  ansible.builtin.include_tasks: install-kubectx.yaml
  when: kubectx_state == 'present'

- name: Include tasks to remove kubectx
  ansible.builtin.include_tasks: remove-kubectx.yaml
  when: kubectx_state == 'absent'
