---
# tasks file for tlp

- name: Set tlp for laptop battery life
  when: laptop and tlp_enabled
  block:
    - name: Install tlp
      ansible.builtin.dnf:
        name:
          - tlp
          - tlp-rdw
        state: "{{ tlp_state }}"

    - name: Remove conflicting power profile daemon
      ansible.builtin.dnf:
        name: power-profiles-daemon
        state: absent

    - name: Ensure tlp is started and enabled at boot
      ansible.builtin.service:
        name: tlp
        state: started
        enabled: true

    - name: Mask conflicting services # noqa: command-instead-of-module
      ansible.builtin.command:
        cmd: systemctl mask systemd-rfkill.service systemd-rfkill.socket
      changed_when: true
