---
- name: Ensure not installed via dnf
  ansible.builtin.dnf:
    name:
      - golang
      - golang-src
    state: absent
    autoremove: true

- name: Ensure golang directory does not exist
  ansible.builtin.file:
    path: /usr/lib/golang
    state: absent

- name: Check if installed
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "command -v {{ go_binary_name }}"
  register: go_installed
  changed_when: false
  failed_when: go_installed.rc != 0 and go_installed.stderr != ""

- name: Get installed version data
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "{{ go_binary_name }} version"
  register: go_installed_version_data
  changed_when: false
  failed_when: "go_installed_version_data.rc != 0 or (go_installed_version_data.rc == 0 and 'go version' not in go_installed_version_data.stdout)"
  when: not go_installed.failed

- name: Set installed version
  ansible.builtin.set_fact:
    go_installed_version: "{{ go_installed_version_data.stdout.split()[2] if not go_installed_version_data.failed else '' }}"

- name: Get the latest release data
  ansible.builtin.uri:
    url: https://go.dev/dl/?mode=json
    return_content: true
    headers:
      Authorization: "{{ 'Bearer ' + github_pat if github_pat is defined else omit }}"
  register: go_latest_release_data

- name: Set the release version
  ansible.builtin.set_fact:
    go_release_version: "{{ go_latest_release_data.json[0].version if go_version == 'latest' else go_version }}"

- name: Download and install
  when: go_installed_version != go_release_version
  block:
    - name: Set the release artifact
      vars:
        arch_name:
          amd: amd64
          arm: arm64
      ansible.builtin.set_fact:
        go_release_artifact: "{{ go_release_version }}.{{ ansible_facts.system | lower }}-{{ arch }}"

    - name: Ensure clean extract path
      ansible.builtin.file:
        path: "{{ go_dir }}"
        state: absent

    - name: Unarchive artifact
      ansible.builtin.unarchive:
        src: "https://go.dev/dl/{{ go_release_artifact }}.tar.gz"
        dest: "/usr/local"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0755"
        remote_src: true

    - name: Give executable permissions to binary
      ansible.builtin.file:
        path: "{{ go_dir }}/bin"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x
        recurse: true

    - name: Ensure gopath directory exists
      ansible.builtin.file:
        path: "{{ go_gopath_dir }}"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0755"

- name: Install go tools
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "go install {{ item }}"
  loop: "{{ go_tools }}"
  changed_when: true
