---
# tasks file for go

- name: Include tasks to install go
  ansible.builtin.include_tasks: install-go.yaml
  when: go_state == 'present'

- name: Include tasks to remove go
  ansible.builtin.include_tasks: remove-go.yaml
  when: go_state == 'absent'
