---
# defaults file for network-tools

network_tools:
  - name: net-tools
    state: latest
  - name: nmap
    state: latest
  - name: iftop
    state: latest
  - name: tcpdump
    state: latest
  - name: traceroute
    state: latest
  - name: whois
    state: latest
