---
# tasks file for sops

- name: Get the latest GitHub release data
  ansible.builtin.uri:
    url: https://api.github.com/repos/getsops/sops/releases/latest
    return_content: true
  register: sops_latest_release_data

- name: Set the release version
  ansible.builtin.set_fact:
    sops_latest_release_version: "{{ sops_latest_release_data.json.tag_name }}"

- name: Set the release artifact
  vars:
    arch_name:
      amd: amd64
      arm: arm64
  ansible.builtin.set_fact:
    sops_release_artifact: "sops-{{ sops_latest_release_version }}.{{ ansible_facts.system | lower }}.{{ arch_name[archs.get(ansible_facts.architecture)] | default(ansible_facts.architecture) }}"

- name: Create download temporary directory
  ansible.builtin.tempfile:
    state: directory
    prefix: sops_
  register: sops_tempdir

- name: Download artifact
  ansible.builtin.get_url:
    url: "https://github.com/getsops/sops/releases/download/{{ sops_latest_release_version }}/{{ sops_release_artifact }}"
    dest: "{{ sops_tempdir.path }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: a+x

- name: Copy binary
  ansible.builtin.copy:
    src: "{{ sops_tempdir.path }}/{{ sops_release_artifact }}"
    dest: /usr/local/bin/sops
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: a+x
    remote_src: true

- name: Cleanup temp files
  ansible.builtin.file:
    path: "{{ sops_tempdir.path }}"
    state: absent
