---
# tasks file for sops

- name: Include tasks to install sops
  ansible.builtin.include_tasks: install-sops.yaml
  when: sops_state == 'present'

- name: Include tasks to remove sops
  ansible.builtin.include_tasks: remove-sops.yaml
  when: sops_state == 'absent'
