---
# tasks file for onefetch

- name: Include tasks to install onefetch
  ansible.builtin.include_tasks: install-onefetch.yaml
  when: onefetch_state == 'present'

- name: Include tasks to remove onefetch
  ansible.builtin.include_tasks: remove-onefetch.yaml
  when: onefetch_state == 'absent'
