---
# tasks file for onefetch

- name: Get the latest GitHub release data
  ansible.builtin.uri:
    url: https://api.github.com/repos/o2sh/onefetch/releases/latest
    return_content: true
  register: onefetch_latest_release_data

- name: Set the latest release version
  ansible.builtin.set_fact:
    onefetch_latest_release_version: "{{ onefetch_latest_release_data.json.tag_name }}"

- name: Set the release artifact
  ansible.builtin.set_fact:
    onefetch_release_artifact: "onefetch-{{ 'win' if ansible_facts.system == 'Windows' else 'mac' if ansible_facts.system == 'Darwin' else 'linux' }}"

- name: Create download temporary directory
  ansible.builtin.tempfile:
    state: directory
    prefix: onefetch_
  register: onefetch_tempdir

- name: Unarchive artifact
  ansible.builtin.unarchive:
    src: "https://github.com/o2sh/onefetch/releases/download/{{ onefetch_latest_release_version }}/{{ onefetch_release_artifact }}.tar.gz"
    dest: "{{ onefetch_tempdir.path }}"
    remote_src: true

- name: Copy binary
  ansible.builtin.copy:
    src: "{{ onefetch_tempdir.path }}/onefetch"
    dest: /usr/local/bin
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: a+x
    remote_src: true

- name: Cleanup temp files
  ansible.builtin.file:
    path: "{{ onefetch_tempdir.path }}"
    state: absent
