---
# tasks file for ghostty

- name: Enable yum repository
  community.general.copr:
    host: copr.fedorainfracloud.org
    state: "{{ 'enabled' if ghostty_state == 'latest' else 'disabled' }}"
    name: pgdev/ghostty

- name: Install ghostty
  ansible.builtin.dnf5:
    name: ghostty
    state: "{{ ghostty_state }}"

- name: Configure ghostty
  block:
    - name: Ensure config directory exists
      ansible.builtin.file:
        path: "/home/{{ username }}/.config/ghostty"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0755"
      register: config_dir

    - name: Copy config
      ansible.builtin.template:
        src: config.j2
        dest: "{{ config_dir.path }}/config"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0644"
