---
- name: Check if installed
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "command -v {{ deno_binary_name }}"
  changed_when: false
  register: deno_installed
  failed_when: deno_installed.rc != 0 and deno_installed.stderr != ""

- name: Get installed version data
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "{{ deno_binary_name }} --version"
  register: deno_installed_version_data
  changed_when: false
  failed_when: "deno_installed_version_data.rc != 0 or (deno_installed_version_data.rc == 0 and 'deno' not in deno_installed_version_data.stdout)"
  when: not deno_installed.failed

- name: Set installed version
  ansible.builtin.set_fact:
    deno_installed_version: "{{ 'v' + deno_installed_version_data.stdout_lines[0].split()[1] if not deno_installed_version_data.failed else '' }}"

- name: Get the latest GitHub release data
  ansible.builtin.uri:
    url: https://api.github.com/repos/denoland/deno/releases/latest
    return_content: true
  register: deno_latest_release_data

- name: Set the release version
  ansible.builtin.set_fact:
    deno_release_version: "{{ deno_latest_release_data.json.tag_name if deno_version == 'latest' else deno_version }}"

- name: Download and install
  when: deno_installed_version != deno_release_version
  block:
    - name: Set the release artifact
      vars:
        arch_name:
          amd: x86_64
          arm: aarch64
      ansible.builtin.set_fact:
        deno_release_artifact: "deno-{{ arch }}-unknown-{{ ansible_facts.system | lower }}-gnu"

    - name: Create download temporary directory
      ansible.builtin.tempfile:
        state: directory
        prefix: deno_
      register: deno_tempdir

    - name: Unarchive artifact
      ansible.builtin.unarchive:
        src: "https://github.com/denoland/deno/releases/download/{{ deno_release_version }}/{{ deno_release_artifact }}.zip"
        dest: "{{ deno_tempdir.path }}"
        remote_src: true

    - name: Copy binary
      ansible.builtin.copy:
        src: "{{ deno_tempdir.path }}/deno"
        dest: "{{ deno_path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x
        remote_src: true

    - name: Cleanup temp files
      ansible.builtin.file:
        path: "{{ deno_tempdir.path }}"
        state: absent
