---
# tasks file for deno

- name: Include tasks to install deno
  ansible.builtin.include_tasks: install-deno.yaml
  when: deno_state == 'present'

- name: Include tasks to remove deno
  ansible.builtin.include_tasks: remove-deno.yaml
  when: deno_state == 'absent'
