---
# tasks file for node

- name: Include tasks to install node
  ansible.builtin.include_tasks: install-node.yaml
  when: node_state == 'present'

- name: Include tasks to remove node
  ansible.builtin.include_tasks: remove-node.yaml
  when: node_state == 'absent'
