---
# defaults file for kubectx

kubectx_state: present
kubectx_version: latest
kubectx_binary_name: kubectx
kubectx_binary_path: "{{ binaries_path }}/{{ kubectx_binary_name }}"

kubectx_archs:
  x86_64: x86_64
  amd64: x86_64
  # x86:
  aarch64: arm64
  arm64: arm64
  armv9l: arm64
  armv8l: arm64
  # armv7l:
  # armv6l:
  # aarch32:
  # s390x:
  # i386:
  # i686:
  # ppc64le:

kubectx_arch: "{{ kubectx_archs.get(ansible_facts.architecture) | default(ansible_facts.architecture) }}"

kubectx_force_download: false

kubectx_latest_version_url: https://api.github.com/repos/ahmetb/kubectx/releases/latest
kubectx_base_download_url: https://github.com/ahmetb/kubectx/releases/download
kubectx_build_lib: gnu
kubectx_artifact_name: "kubectx_{{ kubectx_release_version }}_{{ ansible_facts.system | lower }}_{{ kubectx_arch }}.tar.gz"
kubectx_artifact_download_url: "{{ kubectx_base_download_url }}/{{ kubectx_release_version }}/{{ kubectx_artifact_name }}"
kubectx_artifact_basename: "{{ kubectx_artifact_name | regex_replace('.tar.gz', '') }}"

kubectx_checksum_algorithm: sha256
kubectx_checksum_name: checksums.txt
kubectx_checksum_url: "{{ kubectx_base_download_url }}/{{ kubectx_release_version }}/{{ kubectx_checksum_name }}"
kubectx_checksum: "{{ kubectx_checksum_algorithm }}:{{ kubectx_checksum_url }}"
