---
- name: Check if installed
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "command -v {{ task_binary_name }}"
  register: task_installed
  changed_when: false
  failed_when: task_installed.rc != 0 and task_installed.stderr != ""

- name: Get installed version data
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "{{ task_binary_name }} --version"
  register: task_installed_version_data
  changed_when: false
  failed_when: >
    task_installed_version_data.rc != 0 or not (task_installed_version_data.stdout | regex_search('^\d+\.\d+\.\d+$'))
  when: task_installed.rc == 0

- name: Set installed version
  ansible.builtin.set_fact:
    task_installed_version: "{{ task_installed_version_data.stdout if task_installed.rc == 0 else '' }}"

- name: Get the latest release data
  ansible.builtin.uri:
    url: "{{ task_latest_version_url }}"
    return_content: true
    headers:
      Authorization: "{{ 'Bearer ' + github_pat if github_pat is defined else omit }}"
  register: task_latest_release_data
  retries: 3
  delay: 5

- name: Set the release version
  ansible.builtin.set_fact:
    task_release_version: "{{ task_latest_release_data.json.tag_name if task_version == 'latest' else task_version }}"

- name: Download and install
  when: task_force_download or task_installed_version != task_release_version
  block:
    - name: Create download temporary directory
      ansible.builtin.tempfile:
        state: directory
        prefix: task_
      register: task_tempdir

    - name: Download checksums
      ansible.builtin.get_url:
        url: "{{ task_checksum_url }}"
        dest: "{{ task_tempdir.path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0644"
      register: downloaded_checksums

    - name: Get checksum text content
      ansible.builtin.slurp:
        src: "{{ downloaded_checksums.dest }}"
      register: checksums_data

    - name: Get sha256 text content
      ansible.builtin.set_fact:
        sha256_text: "{{ checksums_data.content | b64decode | trim }}"

    - name: Get search word rhs
      ansible.builtin.set_fact:
        search_word_rhs: "{{ task_artifact_name }}"

    - name: Extract checksum
      ansible.builtin.set_fact:
        task_checksum: "{{ task_checksum_algorithm }}:{{ sha256_text | regex_search('([a-f0-9]{64})\\s+.*' ~ search_word_rhs) | split | first }}"

    - name: Download artifact
      ansible.builtin.get_url:
        url: "{{ task_artifact_download_url }}"
        dest: "{{ task_tempdir.path }}"
        checksum: "{{ task_checksum }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x
      register: downloaded_artifact

    - name: Unarchive artifact
      ansible.builtin.unarchive:
        src: "{{ downloaded_artifact.dest }}"
        dest: "{{ task_tempdir.path }}"
        remote_src: true

    - name: Copy binary
      ansible.builtin.copy:
        src: "{{ task_tempdir.path }}/task"
        dest: "{{ task_binary_path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x
        remote_src: true

    - name: Cleanup temp files
      ansible.builtin.file:
        path: "{{ task_tempdir.path }}"
        state: absent
