---
- name: Check if installed
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "command -v {{ task_binary_name }}"
  register: task_installed
  changed_when: false
  failed_when: task_installed.rc != 0 and task_installed.stderr != ""

- name: Get installed version data
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "{{ task_binary_name }} --version"
  register: task_installed_version_data
  changed_when: false
  failed_when: "task_installed_version_data.rc != 0 or (task_installed_version_data.rc == 0 and 'version' not in task_installed_version_data.stdout)"
  when: task_installed.rc == 0

- name: Set installed version
  ansible.builtin.set_fact:
    task_installed_version: "{{ task_installed_version_data.stdout.split()[2] if task_installed.rc == 0 else '' }}"

- name: Get the latest release data
  ansible.builtin.uri:
    url: https://api.github.com/repos/go-task/task/releases/latest
    return_content: true
    headers:
      Authorization: "{{ 'Bearer ' + github_pat if github_pat is defined else omit }}"
  register: task_latest_release_data

- name: Set the release version
  ansible.builtin.set_fact:
    task_release_version: "{{ task_latest_release_data.json.tag_name if task_version == 'latest' else task_version }}"

- name: Download and install
  when: task_installed_version != task_release_version
  block:
    - name: Set the release artifact
      vars:
        arch_name:
          amd: amd64
          arm: arm64
      ansible.builtin.set_fact:
        task_release_artifact: "task_{{ ansible_facts.system | lower }}_{{ arch }}"

    - name: Create download temporary directory
      ansible.builtin.tempfile:
        state: directory
        prefix: task_
      register: task_tempdir

    - name: Unarchive artifact
      ansible.builtin.unarchive:
        src: "https://github.com/go-task/task/releases/download/{{ task_release_version }}/{{ task_release_artifact }}.tar.gz"
        dest: "{{ task_tempdir.path }}"
        remote_src: true

    - name: Copy binary
      ansible.builtin.copy:
        src: "{{ task_tempdir.path }}/task"
        dest: "{{ task_binary_path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x
        remote_src: true

    - name: Cleanup temp files
      ansible.builtin.file:
        path: "{{ task_tempdir.path }}"
        state: absent
