---
- name: Check if installed
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "command -v {{ fastfetch_binary_name }}"
  register: fastfetch_installed
  changed_when: false
  failed_when: fastfetch_installed.rc != 0 and fastfetch_installed.stderr != ""

- name: Get installed version data
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "{{ fastfetch_binary_name }} --version"
  register: fastfetch_installed_version_data
  changed_when: false
  failed_when: >
    fastfetch_installed_version_data.rc != 0 or (fastfetch_installed_version_data.rc == 0 and 'fastfetch' not in fastfetch_installed_version_data.stdout)
  when: fastfetch_installed.rc == 0

- name: Set installed version
  ansible.builtin.set_fact:
    fastfetch_installed_version: "{{ fastfetch_installed_version_data.stdout.split()[1] if fastfetch_installed.rc == 0 else '' }}"

- name: Get the latest release data
  ansible.builtin.uri:
    url: "{{ fastfetch_latest_version_url }}"
    return_content: true
    headers:
      Authorization: "{{ 'Bearer ' + github_pat if github_pat is defined else omit }}"
  register: fastfetch_latest_release_data
  retries: 3
  delay: 5

- name: Set the release version
  ansible.builtin.set_fact:
    fastfetch_release_version: "{{ fastfetch_latest_release_data.json.tag_name if fastfetch_version == 'latest' else fastfetch_version }}"

- name: Download and install
  when: fastfetch_force_download or fastfetch_installed_version != fastfetch_release_version
  block:
    - name: Create download temporary directory
      ansible.builtin.tempfile:
        state: directory
        prefix: fastfetch_
      register: fastfetch_tempdir

    - name: Get sha256 text content
      ansible.builtin.set_fact:
        sha256_text: "{{ fastfetch_latest_release_data.json.body.split('SHA256SUMs')[1].split('SHA512SUMs')[0].split('```')[1] | trim }}"

    - name: Get search word rhs
      ansible.builtin.set_fact:
        search_word_rhs: "{{ fastfetch_artifact_basename }}/{{ fastfetch_artifact_name }}"

    - name: Extract checksum
      ansible.builtin.set_fact:
        fastfetch_checksum: "{{ fastfetch_checksum_algorithm }}:{{ sha256_text | regex_search('([a-f0-9]{64})\\s+.*' ~ search_word_rhs) | split | first }}"

    - name: Download artifact
      ansible.builtin.get_url:
        url: "{{ fastfetch_artifact_download_url }}"
        dest: "{{ fastfetch_tempdir.path }}"
        checksum: "{{ fastfetch_checksum }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x
      register: downloaded_artifact

    - name: Unarchive artifact
      ansible.builtin.unarchive:
        src: "{{ downloaded_artifact.dest }}"
        dest: "{{ fastfetch_tempdir.path }}"
        remote_src: true

    - name: Copy binary
      ansible.builtin.copy:
        src: "{{ fastfetch_tempdir.path }}/{{ fastfetch_artifact_basename }}/usr/bin/{{ item.name }}"
        dest: "{{ item.dest }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x
        remote_src: true
      loop:
        - name: "{{ fastfetch_binary_name }}"
          dest: "{{ fastfetch_binary_path }}"
        - name: "{{ fastfetch_flashfetch_binary_name }}"
          dest: "{{ fastfetch_flashfetch_binary_path }}"

    - name: Cleanup temp files
      ansible.builtin.file:
        path: "{{ fastfetch_tempdir.path }}"
        state: absent
