---
- name: Check if installed
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "command -v {{ fastfetch_binary_name }}"
  changed_when: false
  register: fastfetch_installed
  failed_when: fastfetch_installed.rc != 0 and fastfetch_installed.stderr != ""

- name: Get installed version data
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "{{ fastfetch_binary_name }} --version"
  register: fastfetch_installed_version_data
  changed_when: false
  failed_when: >
    fastfetch_installed_version_data.rc != 0 or (fastfetch_installed_version_data.rc == 0 and 'fastfetch' not in fastfetch_installed_version_data.stdout)
  when: not fastfetch_installed.failed

- name: Set installed version
  ansible.builtin.set_fact:
    fastfetch_installed_version: "{{ fastfetch_installed_version_data.stdout.split()[1] if not fastfetch_installed_version_data.failed else '' }}"

- name: Get the latest GitHub release data
  ansible.builtin.uri:
    url: https://api.github.com/repos/fastfetch-cli/fastfetch/releases/latest
    return_content: true
  register: fastfetch_latest_release_data

- name: Set the release version
  ansible.builtin.set_fact:
    fastfetch_release_version: "{{ fastfetch_latest_release_data.json.tag_name if fastfetch_version == 'latest' else fastfetch_version }}"

- name: Download and install
  when: fastfetch_installed_version != fastfetch_release_version
  block:
    - name: Set the release artifact
      vars:
        arch_name:
          amd: amd64
          arm: aarch64
      ansible.builtin.set_fact:
        fastfetch_release_artifact: "fastfetch-{{ ansible_facts.system | lower }}-{{ arch }}"

    - name: Create download temporary directory
      ansible.builtin.tempfile:
        state: directory
        prefix: fastfetch_
      register: fastfetch_tempdir

    - name: Unarchive artifact
      ansible.builtin.unarchive:
        src: "https://github.com/fastfetch-cli/fastfetch/releases/download/{{ fastfetch_release_version }}/{{ fastfetch_release_artifact }}.tar.gz"
        dest: "{{ fastfetch_tempdir.path }}"
        remote_src: true

    - name: Copy binary
      ansible.builtin.copy:
        src: "{{ fastfetch_tempdir.path }}/{{ fastfetch_release_artifact }}/usr/bin/{{ item.name }}"
        dest: "{{ item.dest }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x
        remote_src: true
      loop:
        - name: "{{ fastfetch_binary_name }}"
          dest: "{{ fastfetch_path }}"
        - name: "{{ fastfetch_flashfetch_binary_name }}"
          dest: "{{ fastfetch_flashfetch_path }}"

    - name: Cleanup temp files
      ansible.builtin.file:
        path: "{{ fastfetch_tempdir.path }}"
        state: absent
