---
# tasks file for fastfetch

- name: Include tasks to install fastfetch
  ansible.builtin.include_tasks: install-fastfetch.yaml
  when: fastfetch_state == 'present'

- name: Include tasks to remove fastfetch
  ansible.builtin.include_tasks: remove-fastfetch.yaml
  when: fastfetch_state == 'absent'
