---
# defaults file for fastfetch

fastfetch_state: present
fastfetch_version: latest
fastfetch_binary_name: fastfetch
fastfetch_binary_path: "{{ binaries_path }}/{{ fastfetch_binary_name }}"
fastfetch_flashfetch_binary_name: flashfetch
fastfetch_flashfetch_binary_path: "{{ binaries_path }}/{{ fastfetch_flashfetch_binary_name }}"
