---
- name: Check if installed
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: type dust
  changed_when: false
  register: dust_installed
  failed_when: "not ('dust: not found' in dust_installed.stderr or 'dust is' in dust_installed.stdout)"

- name: Get installed version data
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: dust --version
  changed_when: false
  register: dust_installed_version_data
  failed_when: "'Dust' not in dust_installed_version_data.stdout"
  when: dust_installed.rc == 0

- name: Set installed version
  ansible.builtin.set_fact:
    dust_installed_version: "{{ 'v' + dust_installed_version_data.stdout.split()[1] if dust_installed.rc == 0 else '' }}"

- name: Get the latest GitHub release data
  ansible.builtin.uri:
    url: https://api.github.com/repos/bootandy/dust/releases/latest
    return_content: true
  register: dust_latest_release_data

- name: Set the release version
  ansible.builtin.set_fact:
    dust_release_version: "{{ dust_latest_release_data.json.tag_name if dust_version == 'latest' else dust_version }}"

- name: Download and install
  when: dust_installed_version != dust_release_version
  block:
    - name: Set the release artifact
      vars:
        arch_name:
          amd: x86_64
          arm: aarch64
      ansible.builtin.set_fact:
        dust_release_artifact: "dust-{{ dust_release_version }}-{{ arch_name[archs.get(ansible_facts.architecture)] | default(ansible_facts.architecture) }}-unknown-{{ ansible_facts.system | lower }}-gnu"

    - name: Create download temporary directory
      ansible.builtin.tempfile:
        state: directory
        prefix: dust_
      register: dust_tempdir

    - name: Unarchive artifact
      ansible.builtin.unarchive:
        src: "https://github.com/bootandy/dust/releases/download/{{ dust_release_version }}/{{ dust_release_artifact }}.tar.gz"
        dest: "{{ dust_tempdir.path }}"
        remote_src: true

    - name: Copy binary
      ansible.builtin.copy:
        src: "{{ dust_tempdir.path }}/{{ dust_release_artifact }}/dust"
        dest: "{{ dust_path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x
        remote_src: true

    - name: Cleanup temp files
      ansible.builtin.file:
        path: "{{ dust_tempdir.path }}"
        state: absent
