---
- name: Check if installed
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "command -v {{ dust_binary_name }}"
  changed_when: false
  register: dust_installed
  failed_when: dust_installed.rc != 0 and dust_installed.stderr != ""

- name: Get installed version data
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "{{ dust_binary_name }} --version"
  register: dust_installed_version_data
  changed_when: false
  failed_when: "dust_installed_version_data.rc != 0 or (dust_installed_version_data.rc == 0 and 'Dust' not in dust_installed_version_data.stdout)"
  when: not dust_installed.failed

- name: Set installed version
  ansible.builtin.set_fact:
    dust_installed_version: "{{ 'v' + dust_installed_version_data.stdout.split()[1] if not dust_installed_version_data.failed else '' }}"

- name: Set installed version
  ansible.builtin.set_fact:
    dust_installed_version: "{{ 'v' + dust_installed_version_data.stdout.split()[1] if not dust_installed_version_data.failed else '' }}"

- name: Get the latest GitHub release data
  ansible.builtin.uri:
    url: https://api.github.com/repos/bootandy/dust/releases/latest
    return_content: true
    headers:
      Authorization: "{{ 'Bearer ' + github_pat if github_pat is defined else omit }}"
  register: dust_latest_release_data

- name: Set the release version
  ansible.builtin.set_fact:
    dust_release_version: "{{ dust_latest_release_data.json.tag_name if dust_version == 'latest' else dust_version }}"

- name: Download and install
  when: dust_installed_version != dust_release_version
  block:
    - name: Set the release artifact
      vars:
        arch_name:
          amd: x86_64
          arm: aarch64
      ansible.builtin.set_fact:
        dust_release_artifact: "dust-{{ dust_release_version }}-{{ arch }}-unknown-{{ ansible_facts.system | lower }}-gnu"

    - name: Create download temporary directory
      ansible.builtin.tempfile:
        state: directory
        prefix: dust_
      register: dust_tempdir

    - name: Unarchive artifact
      ansible.builtin.unarchive:
        src: "https://github.com/bootandy/dust/releases/download/{{ dust_release_version }}/{{ dust_release_artifact }}.tar.gz"
        dest: "{{ dust_tempdir.path }}"
        remote_src: true

    - name: Copy binary
      ansible.builtin.copy:
        src: "{{ dust_tempdir.path }}/{{ dust_release_artifact }}/dust"
        dest: "{{ dust_path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x
        remote_src: true

    - name: Cleanup temp files
      ansible.builtin.file:
        path: "{{ dust_tempdir.path }}"
        state: absent
