---
# tasks file for dust

- name: Include tasks to install dust
  ansible.builtin.include_tasks: install-dust.yaml
  when: dust_state == 'present'

- name: Include tasks to remove dust
  ansible.builtin.include_tasks: remove-dust.yaml
  when: dust_state == 'absent'
