---
# defaults file for tlrc

tlrc_state: present
tlrc_version: latest
tlrc_binary_name: tldr
tlrc_binary_path: "{{ binaries_path | default('/usr/local/bin') }}/{{ tlrc_binary_name }}"

tlrc_archs:
  x86_64: x86_64
  amd64: x86_64
  # x86:
  aarch64: x86_64
  arm64: x86_64
  armv9l: x86_64
  armv8l: x86_64
  # armv7l:
  # armv6l:
  # aarch32:
  # s390x:
  # i386:
  # i686:
  # ppc64le:

tlrc_arch: "{{ tlrc_archs.get(ansible_facts.architecture) | default(ansible_facts.architecture) }}"

tlrc_force_download: false

tlrc_latest_version_url: https://api.github.com/repos/tldr-pages/tlrc/releases/latest
tlrc_base_download_url: https://github.com/tldr-pages/tlrc/releases/download
tlrc_build_lib: gnu
tlrc_artifact_name: "tlrc-{{ tlrc_release_version }}-{{ tlrc_arch }}-unknown-{{ ansible_facts.system | lower }}-{{ tlrc_build_lib }}.tar.gz"
tlrc_artifact_download_url: "{{ tlrc_base_download_url }}/{{ tlrc_release_version }}/{{ tlrc_artifact_name }}"
tlrc_artifact_basename: "{{ tlrc_artifact_name | regex_replace('.tar.gz', '') }}"
