---
# tasks file for eza

- name: Include tasks to install eza
  ansible.builtin.include_tasks: install-eza.yaml
  when: eza_state == 'present'

- name: Include tasks to remove eza
  ansible.builtin.include_tasks: remove-eza.yaml
  when: eza_state == 'absent'
