---
# tasks file for eza

- name: Get the latest GitHub release data
  ansible.builtin.uri:
    url: https://api.github.com/repos/eza-community/eza/releases/latest
    return_content: true
  register: eza_latest_release_data

- name: Set the latest release version
  ansible.builtin.set_fact:
    eza_latest_release_version: "{{ eza_latest_release_data.json.tag_name }}"

- name: Set the release artifact
  vars:
    arch_name:
      amd: x86_64
      arm: aarch64
  ansible.builtin.set_fact:
    eza_release_artifact: "eza_{{ arch_name[archs.get(ansible_facts.architecture)] | default(ansible_facts.architecture) }}-unknown-{{ ansible_facts.system }}-gnu"

- name: Create download temporary directory
  ansible.builtin.tempfile:
    state: directory
    prefix: eza_
  register: eza_tempdir

- name: Unarchive artifact
  ansible.builtin.unarchive:
    src: "https://github.com/eza-community/eza/releases/download/{{ eza_latest_release_version }}/{{ eza_release_artifact }}.tar.gz"
    dest: "{{ eza_tempdir.path }}"
    remote_src: true

- name: Copy binary
  ansible.builtin.copy:
    src: "{{ eza_tempdir.path }}/eza"
    dest: /usr/local/bin/
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: a+x
    remote_src: true

- name: Cleanup temp files
  ansible.builtin.file:
    path: "{{ eza_tempdir.path }}"
    state: absent
