---
- name: Ensure removed
  ansible.builtin.command: # noqa no-changed-when
    cmd: "{{ nix_installer_binary_path }} uninstall --no-confirm"
  # ansible.builtin.file:
  #   path: "{{ nix_binary_path }}"
  #   state: absent
