---
# tasks file for docker

- name: Include tasks to install docker
  ansible.builtin.include_tasks: install-docker.yaml
  when: docker_state == 'latest'

- name: Include tasks to remove docker
  ansible.builtin.include_tasks: remove-docker.yaml
  when: docker_state == 'absent'
