---
- name: Check if installed
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "command -v {{ jq_binary_name }}"
  register: jq_installed
  changed_when: false
  failed_when: jq_installed.rc != 0 and jq_installed.stderr != ""

- name: Get installed version data
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "{{ jq_binary_name }} --version"
  register: jq_installed_version_data
  changed_when: false
  failed_when: "jq_installed_version_data.rc != 0 or (jq_installed_version_data.rc == 0 and 'jq' not in jq_installed_version_data.stdout)"
  when: jq_installed.rc == 0

- name: Set installed version
  ansible.builtin.set_fact:
    jq_installed_version: "{{ jq_installed_version_data.stdout if jq_installed.rc == 0 else '' }}"

- name: Get the latest release data
  ansible.builtin.uri:
    url: "{{ jq_latest_version_url }}"
    return_content: true
    headers:
      Authorization: "{{ 'Bearer ' + github_pat if github_pat is defined else omit }}"
  register: jq_latest_release_data
  retries: 3
  delay: 5

- name: Set the release version
  ansible.builtin.set_fact:
    jq_release_version: "{{ jq_latest_release_data.json.tag_name if jq_version == 'latest' else jq_version }}"

- name: Download and install
  when: jq_force_download or jq_installed_version != jq_release_version
  block:
    - name: Create download temporary directory
      ansible.builtin.tempfile:
        state: directory
        prefix: jq_
      register: jq_tempdir

    - name: Download checksums
      ansible.builtin.get_url:
        url: "{{ jq_checksum_url }}"
        dest: "{{ jq_tempdir.path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0644"
      register: downloaded_checksums

    - name: Get checksum text content
      ansible.builtin.slurp:
        src: "{{ downloaded_checksums.dest }}"
      register: checksums_data

    - name: Get sha256 text content
      ansible.builtin.set_fact:
        sha256_text: "{{ checksums_data.content | b64decode | trim }}"

    - name: Get search word rhs
      ansible.builtin.set_fact:
        search_word_rhs: "{{ jq_artifact_name }}"

    - name: Extract checksum
      ansible.builtin.set_fact:
        jq_checksum: "{{ jq_checksum_algorithm }}:{{ sha256_text | regex_search('([a-f0-9]{64})\\s+.*' ~ search_word_rhs) | split | first }}"

    - name: Download artifact
      ansible.builtin.get_url:
        url: "{{ jq_artifact_download_url }}"
        dest: "{{ jq_tempdir.path }}"
        checksum: "{{ jq_checksum }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x

    - name: Copy binary
      ansible.builtin.copy:
        src: "{{ jq_tempdir.path }}/{{ jq_artifact_basename }}"
        dest: "{{ jq_binary_path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x
        remote_src: true

    - name: Cleanup temp files
      ansible.builtin.file:
        path: "{{ jq_tempdir.path }}"
        state: absent
