---
- name: Check if installed
  ansible.builtin.command:
    cmd: type jq
  changed_when: false
  register: jq_installed
  failed_when: "not ('jq: not found' in jq_installed.stderr or 'jq is' in jq_installed.stdout)"

- name: Get installed version data
  ansible.builtin.command:
    cmd: jq --version
  changed_when: false
  register: jq_installed_version_data
  failed_when: "'jq' not in jq_installed_version_data.stdout"
  when: jq_installed.rc == 0

- name: Set installed version
  ansible.builtin.set_fact:
    jq_installed_version: "{{ jq_installed_version_data.stdout if jq_installed.rc == 0 else '' }}"

- name: Get the latest GitHub release data
  ansible.builtin.uri:
    url: https://api.github.com/repos/jqlang/jq/releases/latest
    return_content: true
  register: jq_latest_release_data

- name: Set the release version
  ansible.builtin.set_fact:
    jq_release_version: "{{ jq_latest_release_data.json.tag_name if jq_version == 'latest' else jq_version }}"

- name: Download and install
  when: jq_installed_version != jq_release_version
  block:
    - name: Set the release artifact
      vars:
        arch_name:
          amd: amd64
          arm: arm64
      ansible.builtin.set_fact:
        jq_release_artifact: "jq-{{ ansible_facts.system | lower }}-{{ arch_name[archs.get(ansible_facts.architecture)] | default(ansible_facts.architecture) }}"

    - name: Create download temporary directory
      ansible.builtin.tempfile:
        state: directory
        prefix: jq_
      register: jq_tempdir

    - name: Download artifact
      ansible.builtin.get_url:
        url: "https://github.com/jqlang/jq/releases/download/{{ jq_release_version }}/{{ jq_release_artifact }}"
        dest: "{{ jq_tempdir.path }}"
        mode: a+x

    - name: Copy binary
      ansible.builtin.copy:
        src: "{{ jq_tempdir.path }}/{{ jq_release_artifact }}"
        dest: /usr/local/bin/jq
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x
        remote_src: true

    - name: Cleanup temp files
      ansible.builtin.file:
        path: "{{ jq_tempdir.path }}"
        state: absent
