---
- name: Check if installed
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "command -v {{ jq_binary_name }}"
  register: jq_installed
  changed_when: false
  failed_when: jq_installed.rc != 0 and jq_installed.stderr != ""

- name: Get installed version data
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "{{ jq_binary_name }} --version"
  register: jq_installed_version_data
  changed_when: false
  failed_when: "jq_installed_version_data.rc != 0 or (jq_installed_version_data.rc == 0 and 'jq' not in jq_installed_version_data.stdout)"
  when: jq_installed.rc == 0

- name: Set installed version
  ansible.builtin.set_fact:
    jq_installed_version: "{{ jq_installed_version_data.stdout if jq_installed.rc == 0 else '' }}"

- name: Get the latest GitHub release data
  ansible.builtin.uri:
    url: https://api.github.com/repos/jqlang/jq/releases/latest
    return_content: true
    headers:
      Authorization: "{{ 'Bearer ' + github_pat if github_pat is defined else omit }}"
  register: jq_latest_release_data

- name: Set the release version
  ansible.builtin.set_fact:
    jq_release_version: "{{ jq_latest_release_data.json.tag_name if jq_version == 'latest' else jq_version }}"

- name: Download and install
  when: jq_installed_version != jq_release_version
  block:
    - name: Set the release artifact
      vars:
        arch_name:
          amd: amd64
          arm: arm64
      ansible.builtin.set_fact:
        jq_release_artifact: "jq-{{ ansible_facts.system | lower }}-{{ arch }}"

    - name: Create download temporary directory
      ansible.builtin.tempfile:
        state: directory
        prefix: jq_
      register: jq_tempdir

    - name: Download artifact
      ansible.builtin.get_url:
        url: "https://github.com/jqlang/jq/releases/download/{{ jq_release_version }}/{{ jq_release_artifact }}"
        dest: "{{ jq_tempdir.path }}"
        mode: a+x

    - name: Copy binary
      ansible.builtin.copy:
        src: "{{ jq_tempdir.path }}/{{ jq_release_artifact }}"
        dest: "{{ jq_binary_path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: a+x
        remote_src: true

    - name: Cleanup temp files
      ansible.builtin.file:
        path: "{{ jq_tempdir.path }}"
        state: absent
