---
# tasks file for jq

- name: Get the latest GitHub release data
  ansible.builtin.uri:
    url: https://api.github.com/repos/jqlang/jq/releases/latest
    return_content: true
  register: jq_latest_release_data

- name: Set the latest release version
  ansible.builtin.set_fact:
    jq_latest_release_version: "{{ jq_latest_release_data.json.tag_name }}"

- name: Set the release artifact
  vars:
    arch_name:
      amd: amd64
      arm: arm64
  ansible.builtin.set_fact:
    jq_release_artifact: "jq-{{ ansible_facts.system | lower }}-{{ arch_name[archs.get(ansible_facts.architecture)] | default(ansible_facts.architecture) }}"

- name: Create download temporary directory
  ansible.builtin.tempfile:
    state: directory
    prefix: jq_
  register: jq_tempdir

- name: Download artifact
  ansible.builtin.get_url:
    url: "https://github.com/jqlang/jq/releases/download/{{ jq_latest_release_version }}/{{ jq_release_artifact }}"
    dest: "{{ jq_tempdir.path }}"
    mode: a+x

- name: Copy binary
  ansible.builtin.copy:
    src: "{{ jq_tempdir.path }}/{{ jq_release_artifact }}"
    dest: /usr/local/bin/jq
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: a+x
    remote_src: true

- name: Cleanup temp files
  ansible.builtin.file:
    path: "{{ jq_tempdir.path }}"
    state: absent
