---
# tasks file for jq

- name: Include tasks to install jq
  ansible.builtin.include_tasks: install-jq.yaml
  when: jq_state == 'present'

- name: Include tasks to remove jq
  ansible.builtin.include_tasks: remove-jq.yaml
  when: jq_state == 'absent'
