---
# tasks file for tlrc

- name: Include tasks to install tlrc
  ansible.builtin.include_tasks: install-tlrc.yaml
  when: tlrc_state == 'present'

- name: Include tasks to remove tlrc
  ansible.builtin.include_tasks: remove-tlrc.yaml
  when: tlrc_state == 'absent'
