---
# tasks file for grub

- name: Get grub menu entries
  ansible.builtin.shell: set -o pipefail; grep -P "^menuentry" /boot/grub2/grub.cfg | cut -d "'" -f2
  changed_when: "'Windows Boot Manager' not in grub_entries.stdout"
  register: grub_entries
  when: grub_dual_boot

- name: Copy grub configuration file
  ansible.builtin.template:
    src: grub.j2
    dest: /etc/default/grub
    owner: root
    group: root
    mode: "0644"
  notify: Regenerate GRUB configuration file
