---
# tasks file for zellij

- name: Include tasks to install zellij
  ansible.builtin.include_tasks: install-zellij.yaml
  when: zellij_state == 'present'

- name: Include tasks to remove zellij
  ansible.builtin.include_tasks: remove-zellij.yaml
  when: zellij_state == 'absent'
