---
# tasks file for ksops

- name: Include tasks to install ksops
  ansible.builtin.include_tasks: install-ksops.yaml
  when: ksops_state == 'present'

- name: Include tasks to remove ksops
  ansible.builtin.include_tasks: remove-ksops.yaml
  when: ksops_state == 'absent'
