---
# tasks file for ksops

- name: Get the latest GitHub release data
  ansible.builtin.uri:
    url: https://api.github.com/repos/viaduct-ai/kustomize-sops/releases/latest
    return_content: true
  register: ksops_latest_release_data

- name: Set the latest release version
  ansible.builtin.set_fact:
    ksops_latest_release_version: "{{ ksops_latest_release_data.json.tag_name }}"

- name: Set the release artifact
  vars:
    arch_name:
      amd: x86_64
      arm: arm64
  ansible.builtin.set_fact:
    ksops_release_artifact: "ksops_{{ ksops_latest_release_version[1:] }}_{{ ansible_facts.system }}_{{ arch_name[archs.get(ansible_facts.architecture)] | default(ansible_facts.architecture) }}"

- name: Create download temporary directory
  ansible.builtin.tempfile:
    state: directory
    prefix: ksops_
  register: ksops_tempdir

- name: Unarchive artifact
  ansible.builtin.unarchive:
    src: "https://github.com/viaduct-ai/kustomize-sops/releases/download/{{ ksops_latest_release_version }}/{{ ksops_release_artifact }}.tar.gz"
    dest: "{{ ksops_tempdir.path }}"
    remote_src: true

- name: Copy binary
  ansible.builtin.copy:
    src: "{{ ksops_tempdir.path }}/ksops"
    dest: /usr/local/bin/
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: a+x
    remote_src: true

- name: Cleanup temp files
  ansible.builtin.file:
    path: "{{ ksops_tempdir.path }}"
    state: absent
