---
# tasks file for fonts

- name: Set the fonts directory fact
  ansible.builtin.set_fact:
    fonts_directory: "{{ fonts_system_directory if fonts_installation == 'system' else fonts_user_directory }}"

- name: Ensure fonts directory exists
  ansible.builtin.file:
    path: "{{ fonts_directory }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Get the Nerd Fonts latest GitHub release
  ansible.builtin.uri:
    url: https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest
    return_content: true
    headers:
      Authorization: "{{ 'Bearer ' + github_pat if github_pat is defined else omit }}"
  register: fonts_nerd_fonts_latest_release_data
  retries: 3
  delay: 5

- name: Set the latest Nerd Fonts version
  ansible.builtin.set_fact:
    fonts_nerd_fonts_latest_version: "{{ fonts_nerd_fonts_latest_release_data.json.tag_name }}"

- name: Ensure individual font directories exist
  ansible.builtin.file:
    path: "{{ fonts_directory }}/{{ item.name }}"
    state: directory
    owner: "{{ 'root' if fonts_installation == 'system' else username }}"
    group: "{{ 'root' if fonts_installation == 'system' else username }}"
    mode: "0755"
  loop: "{{ fonts_nerd_fonts | selectattr('state', '==', 'present') }}"

- name: Unarchive remote Nerd Fonts
  ansible.builtin.unarchive:
    src: "https://github.com/ryanoasis/nerd-fonts/releases/download/{{ fonts_nerd_fonts_latest_version }}/{{ item.name }}.tar.xz"
    dest: "{{ fonts_directory }}/{{ item.name }}"
    owner: "{{ 'root' if fonts_installation == 'system' else username }}"
    group: "{{ 'root' if fonts_installation == 'system' else username }}"
    mode: "0644"
    remote_src: true
  loop: "{{ fonts_nerd_fonts | selectattr('state', '==', 'present') }}"
  notify: Update font cache

- name: Copy Microsoft fonts
  ansible.builtin.copy:
    src: microsoft
    dest: "{{ fonts_directory }}"
    owner: "{{ 'root' if fonts_installation == 'system' else username }}"
    group: "{{ 'root' if fonts_installation == 'system' else username }}"
    mode: "0755"
  when: fonts_enable_microsoft
  notify: Update font cache

- name: Remove microsoft fonts
  ansible.builtin.file:
    path: "{{ fonts_directory }}/microsoft"
    state: absent
  when: not fonts_enable_microsoft
  notify: Update font cache

- name: Remove unwanted Nerd Fonts
  ansible.builtin.file:
    path: "{{ fonts_directory }}/{{ item.name }}"
    state: absent
  loop: "{{ fonts_nerd_fonts | selectattr('state', '==', 'absent') }}"
